### ISSUE TITLE
Rollup table

### ISSUE THREAD

**Issue by kiwiz** [etsy/411#10]
Some of the queries that 411 uses are expensive and the results never change. The Dashboard queries are a good example of this. Rather than recomputing this information every time someone loads the page, just generate it at the end of the day.

**Comment by sql25951** [comment]
I like this idea too. Show users a cached version, and place a refresh button there for those who care :)

**Comment by kiwiz** [comment]
We're using ES to power these queries and it runs much faster. Closing for now.
