### ISSUE TITLE
Unclear how to search a particular ES source when multiple ES sources are configured

### ISSUE THREAD

**Issue by clarenceb** [etsy/411#100]
On this page https://github.com/etsy/411/blob/master/docs/HowTo/NewESSource.md it describes how to add additional ES sources by editing the `config.php` file.  However, its unclear to me how to direct a "Logstash" search to a particular ES source.

* Will my search run against all ES sources defined?
* Am I supposed to add something to my ESQuery line to target the particular ES source?

This might just be more of a documentation thing or perhaps I am misunderstanding how this is supposed to work?

**Comment by kiwiz** [comment]
Getting this to work is more difficult than necessary, see #3. I'll make it a high priority to get a better solution that doesn't involve creating a new class.

**Comment by clarenceb** [comment]
Ok, thanks.  Rather than storing the ES API URL in `config.php`, could this not just be stored in the `searches` table much like the URL is stored for `HTTP` searches?  It should be (?) pretty simple to type in the ES API URL for Logstash searches (e.g. just about the query field) and store this with the search data.  From the UX point-of-view, it might get repetitive after a while, where a drop-down with known ES API URLs would be more convenient.

**Comment by kiwiz** [comment]
This should be resolved per #4. :]

If you're feeling adventurous, you can test out the new `ES` search type on HEAD. I've got some odds n ends to clean up before I push out v1.2 proper.

**Comment by kiwiz** [comment]
Out in v1.2.0
