### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by mareban** [etsy/411#102]
Hello,

411 is installed and configured with mysql !

When i update something in a search, i've got this error message :"No change description provided" !!!

261] except [NONE] FOO\\ValidationException: "No change description provided" at [/var/www/411/phplib/REST/Searches.php:86] 0:[FOO\\Searches_REST->beforeStore() called at [/var/www/411/phplib/REST/Models.php:212]] 1:[FOO\\Models_REST->update() called at [/var/www/411/phplib/REST/Models.php:285]] 2:[FOO\\Models_REST->PUT() called at [/var/www/411/phplib/REST.php:109]] 3:[FOO\\REST->route() called at [/var/www/411/htdocs/api/searches.php:6]], 

Can someone help me please !

Thanks for your help.

**Comment by kiwiz** [comment]
- Are you sure you've provided a change description? :]
- What version of 411 are you running?

**Comment by kiwiz** [comment]
Closing, please reopen if you still have problems.
