### ISSUE TITLE
SQLSTATE[23000} | Error when trying to add a new user

### ISSUE THREAD

**Issue by vmcleitao** [etsy/411#104]
I am trying to add a new user on 411 Alert  but I get the following error,

SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: users.site_id, users.api_key

Anyone knows how can I fixed it?

Tks in advance,

VML

**Comment by ChristiaanDouma** [comment]
Yes, 


Add an apikey in de table for the previous created user. It's a bug that the apikey doesn't get saved when creating an user. 

Forgot to create an issue for it.

**Comment by vmcleitao** [comment]
Hi Christian,

I tried several ways to generate a different API Key but the error remains. It occurs with any user that I have been created.

Sincerely

**Comment by ChristiaanDouma** [comment]
I know, you can't fix this in the frontend. You have to open the database from prompt and update the table manuel.


Btw. I am not a maintainer but only user.

**Comment by kiwiz** [comment]
@vmcleitao Should be fixed in v1.2.0

**Comment by kiwiz** [comment]
Closing, please reopen if you still have problems.

**Comment by ChristiaanDouma** [comment]
Seems still an issue. See #108
