### ISSUE TITLE
/assets/css/___.css files missing

### ISSUE THREAD

**Issue by LilRoro** [etsy/411#105]
Running V1.1.0 from the Release page works great - THANK YOU. 
If I clone the current code, and try to run it / modify it to use multiple ES clusters (like explained in issues 3 and 100) - the page will not load as it is missing bootstrap.css,select2.css,select2-bootstrap.css,datetimepicker.css,tablesorter-bootstrap.css,cidemirror.css,dragula.css in the assets/css dir.  This dir doesnt exist in the V1.1.0 version, is it supposed to be pulled down with composer?  What am I missing?

Thanks so much, in advance!

**Comment by kiwiz** [comment]
Hi there,
A dev build needs a few more dependencies. See here for details: https://github.com/etsy/411/blob/master/docs/Development.md#setup

The tl;dr
```
$ npm install
$ bower install
$ composer install
$ grunt prod # 'grunt dev' if you plan on making any js/css changes.
```

**Comment by LilRoro** [comment]
That's it!  Thank you, again!
