### ISSUE TITLE
Elasticsearch 5

### ISSUE THREAD

**Issue by sts** [etsy/411#106]
Upgrade 411 to Elasticsearch 5. Whats needed, collect bugs here.

[Elasticsearch breaking changes documentation.](
https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking-changes-5.0.html)

- [x] #84 Unable to create searches with ES 5.0
- [x] #101 Error getting active count data

## Libraries
- https://github.com/elastic/elasticsearch-php - 5.x branch - [breaking changes](https://github.com/elastic/elasticsearch-php/blob/master/BREAKING_CHANGES.md)
- https://github.com/kiwiz/esquery - missing - look at [src/Result.php](https://github.com/kiwiz/esquery/blob/master/src/Result.php)
- https://github.com/kiwiz/ecl - investigate

**Comment by sts** [comment]
Note, I'm not working on this actively, just wanted to get the discussion going about whats needed.

**Comment by kiwiz** [comment]
I've added experimental support for 5.0 on the es-5.x branch. Try it out and let me know if there are any issues.

**Comment by hex2a** [comment]
LGTM, is there any ETA for a (beta) release?

**Comment by kiwiz** [comment]
I'll hopefully have time to cut a release for the 5.x branch later this week. Marking this issue as completed.
