### ISSUE TITLE
Alerts not dissapearing

### ISSUE THREAD

**Issue by sql25951** [etsy/411#111]
We have 91k alerts in the system now. ALL searches are set to auto-resolve. 

However I can still see all the old alerts on the Alerts tab.

What is the behavior supposed to be there? Do all alerts live forever?

I wondered if the resolving function might have broken due to a high number of alerts suddenly.(mal-functioning search)

**Comment by sql25951** [comment]
Could you make it possible to cleanse the DB via an admin panel button in the Ui? or instructions to do this via the backend also doable.

**Comment by kiwiz** [comment]
I've just tested auto-resolution and it appears to be working fine. Can you check your error logs? It's possible that the PHP worker is running out of memory while trying to resolve the alerts.

Regarding cleanup: The easiest way to do that would probably be via SQL. Something like the following would work: `UPDATE alerts SET state=2 WHERE search_id=<search_id_here>`.

Afterwards, you'll need to resync ES with the MySQL database: `bin/es_sync.php`

**Comment by sql25951** [comment]
yea, great. In this case we're going to cleanse the db, since I think it filled up due to some error in a particular search.
