### ISSUE TITLE
idea: Table view for alert auditing

### ISSUE THREAD

**Issue by sql25951** [etsy/411#113]
This system is very clicky, with no easy way to check your alert rules for errors.

There are two possible solutions: 

1. export rules to csv (if theres a db, this should be fairly simple)
2. table view (all fields possible in a simple table with 1 search per row)

**Comment by kiwiz** [comment]
Not quite what you're asking for, but you can hit the `/api/search` endpoint to get all the searches in JSON format.

**Comment by sql25951** [comment]
we'll try this, Thanks mate.
