### ISSUE TITLE
Logstash search issue

### ISSUE THREAD

**Issue by sql25951** [etsy/411#115]
So we have a search like this:

`type:db message:"string to match"`

The behavior is very bizarre. It seems to be matching on those terms `string to match`, but not sequentially. It matches on term 1,2,3 as they exist ANYWHERE in any order. This leads to false positive searches.

Am I missing something simple with encapsulation? 

When you get to something complex like:

`type:db duration_ms:>800 NOT message:"statement COPY"`

I think its translating this to SELECT * WHERE InString **type:db** AND InString **duration_ms** and NOT InString **message:statement** AND InString **Copy**

Can you confirm the behavior of spaces in the Logstash query, and how we could reliably get strings to behave themselves when inside quotation marks.

**Comment by kiwiz** [comment]
Nope, you're not! The query's currently built up by `AND`ing each component within the query. Our queries operate on tokens (for the most part), so we don't have this issue. I'll have to think a bit about how to fix this... but it will require changes to the [grammar](https://github.com/kiwiz/esquery/blob/master/grammar.pegjs). Thoughts/suggestions are welcome.

**Comment by sql25951** [comment]
I've been thinking about this, it might be fixed by another layer of code which just keeps some calculations going.

example: I have a log message like this:

"This is a really long string and stuff within which I wish to find a string somewhere in the middle which I can then alert on."

My alert is message:"which I wish" 
I'm referring to these as token i ii and iii.

So your search system tokenizes each word (i,ii,iii) and puts AND automatically etc. Then it has this special new inString function where it moves through the message until it finds the first match, then the method notes the distance from the left (x) and the token length `LEN(i)`. Then the search function starts searching again from position `x+LEN(i)+chars`. The search will return false however if It cannot find (ii) after (i) within `LEN(ii)` +~ any separating characters.

**Comment by sql25951** [comment]
chars are spaces or whatever grammar separates your terms in the string e.g ?!@#$%^&*()/\

**Comment by kiwiz** [comment]
Hi, I took a look in the code and it looks like spaces are escaped correctly.
`db:"one two"` gets translated to `one\ two`, which is equivalent. Can you provide some data for reproducing your issue?

**Comment by sql25951** [comment]
ok, ill retry the test case we had.

**Comment by sql25951** [comment]
Just confirming the steps to reproduce. We're using the 'ES' type.
I looked for any long message string. and found one suitable which contained two words which werent consecutive.  My 411 query was: message:"ical query" ran that as a test over a 1hr time-period and it false matched a whole bunch of messages which contained 'ical' then 'query' about 2 lines down. So basically it doesnt care about consecutive, it doesnt care what order, or where in the string.

**Comment by kiwiz** [comment]
Pushed out a potential fix to the issue. Can you test and report back?

**Comment by sql25951** [comment]
Will do, pretty busy this end right now, but its on the list.

**Comment by sql25951** [comment]
Yep, appears fixed. I found a long string and tried searching for it.(worked) I then tried searching for 3 words in the string which were separated (non-linear) which came up 'no results'. Nice work Kai!
