### ISSUE TITLE
Lists Enhancement

### ISSUE THREAD

**Issue by gromit6891** [etsy/411#119]
With the Lists feature, would it be possible to get this to recognize CIDRs or IP ranges as well as single IP Lists?
E.g. 1.116.0.0/15 or 1.10.16.0-1.10.31.255

**Comment by kiwiz** [comment]
I think this might work out of the box? If not, I don't know about implementing it. It would require adding a type field to each list.

**Comment by kiwiz** [comment]
Closing for now. Feel free to reopen if thee's interest.
