### ISSUE TITLE
Searches not saved after reboot

### ISSUE THREAD

**Issue by joe1187** [etsy/411#120]
I can create some searches in 411 (Alerts > Searches > Create). The searches work and results are returned. When i reboot the VMs the searches are not present but the results are. The results change from the configured rule name (created from the search) to unknown. The search type is ES and the sources have been either Ossec or Syslog. 
 
with a previous installation i could reboot and the searches would persist.
 
Any help would be massively appreciated.

**Comment by kiwiz** [comment]
Sanity check: Are you running 411 via the docker image?
