### ISSUE TITLE
ES 5.x - X-pack username and password support

### ISSUE THREAD

**Issue by mk40us** [etsy/411#123]
We have ES 5.x cluster that has x-pack on it. It does not appear that i can pass the username and password via the config.php settings. Is it possible to fix this issue?

**Comment by mk40us** [comment]
I get the below error on the UI when i pass the credentials in the below format 

'hosts' => ['http://username:password@localhost:9200'],


SearchException: {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication token for REST request [/logstash-2017.05.08/_search?ignore_unavailable=true]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication token for REST request [/logstash-2017.05.08/_search?ignore_unavailable=true]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}

**Comment by kiwiz** [comment]
Hi, was this issue resolved?
