### ISSUE TITLE
DB problem error after a hard restart

### ISSUE THREAD

**Issue by missnebun** [etsy/411#124]
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 11 malformed database schema (lists_type_idx) - no such table: main.searches in /var/www/411/phplib/DB.php:81
Stack trace:
#0 /var/www/411/phplib/DB.php(81): PDO->prepare('SELECT * FROM `...')
#1 /var/www/411/phplib/Model.php(494): FOO\DB::query('SELECT * FROM `...', Array)
#2 /var/www/411/phplib/Model.php(466): FOO\ModelFinder::getByQuery(Array)
#3 /var/www/411/phplib/Auth.php(24): FOO\ModelFinder::getById(NULL)
#4 /var/www/411/phplib/411bootstrap.php(66): FOO\Auth::init()
#5 /var/www/411/bin/migration.php(7): require_once('/var/www/411/ph...')
#6 {main}
  thrown in /var/www/411/phplib/DB.php on line 81
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 11 malformed database schema (lists_type_idx) - no such table: main.searches in /var/www/411/phplib/DB.php:81
Stack trace:
#0 /var/www/411/phplib/DB.php(81): PDO->prepare('SELECT `value` ...')
#1 /var/www/411/phplib/DBArray.php(40): FOO\DB::query('SELECT `value` ...', Array, 1)
#2 /var/www/411/phplib/Cookie.php(187): FOO\DBArray->offsetGet('cookie_secret')
#3 /var/www/411/phplib/Cookie.php(91): FOO\Cookie::getKey()
#4 /var/www/411/phplib/Cookie.php(106): FOO\Cookie::generate(Array, 1496269715)
#5 /var/www/411/phplib/Cookie.php(33): FOO\Cookie::write()
#6 [internal function]: FOO\Cookie::FOO\{closure}()
#7 {main}
  thrown in /var/www/411/phplib/DB.php on line 81

**Comment by kiwiz** [comment]
Not familiar with this error, but a quick indicates your DB may be corrupted: http://froebe.net/blog/2015/05/27/error-sqlite-database-is-malformed-solved/
