### ISSUE TITLE
IP not shown if enricher fails

### ISSUE THREAD

**Issue by hex2a** [etsy/411#126]
It is not possible to disable the IP enricher, even if there is a null enricher configured for the field.

If the lookup fails, the IP address is not shown at all
![image](https://user-images.githubusercontent.com/8384544/26975825-b51bdbc4-4d21-11e7-9e32-4d2b50585030.png)

**Comment by kiwiz** [comment]
Fixed with https://github.com/etsy/411/commit/7101e1256254bab4ea5c247e681a936156d02ab5.
