### ISSUE TITLE
Custom Enricher

### ISSUE THREAD

**Issue by vladiber** [etsy/411#127]
I developed my own enricher that make LDAP query to retreive user detals as array. When i pressed test it's works fine , but the Job return Failure status.
Thanks

**Comment by kiwiz** [comment]
Can you check the error logs and see what (if any) errors are being reported?

**Comment by vladiber** [comment]
This is the error received from worker job:

except [NONE] Errno 2: "htmlentities() expects parameter 1 to be string, array given" at [/var/www/411/phplib/Util.php:48] 0:[htmlentities() called at [/var/www/411/phplib/Util.php:48]] 1:[FOO\Util::escape() called at [/var/www/411/phplib/Enricher/Null.php:13]] 2:[FOO\Null_Enricher::processHTML() called at [/var/www/411/phplib/Notification.php:264]] 3:[FOO\Notification::renderAlerts() called at [/var/www/411/phplib/Notification.php:42]] 4:[FOO\Notification::sendAlertEmail() called at [/var/www/411/phplib/Job/Search.php:116]] 5:[FOO\Search_Job->_run() called at [/var/www/411/phplib/Job/Search.php:29]] 6:[FOO\Search_Job->run() called at [/var/www/411/phplib/Worker.php:105]] 7:[FOO\Worker->processSite() called at [/var/www/411/bin/worker.php:34]]

**Comment by kiwiz** [comment]
That's odd, can you show me the source for your Enricher + the list of enable filters on the search?

**Comment by vladiber** [comment]
<?php

namespace FOO;

/**
 * IP Enricher
 * Return GeoIP information on an IP address.
 * @package FOO
 */
class AD_Enricher extends Enricher {
    public static $TYPE = 'user';
    public static function process($data) {
        set_time_limit(30);
        error_reporting(E_ALL);
        ini_set('error_reporting', E_ALL);
        ini_set('display_errors',1);
        $ldapserver = 'server-ip';
        $ldapuser      = 'cn=xxxx,cn=xxx,dc=xx,dc=xx';
        $ldappass     = 'pass';
        $ldaptree    = "DC=xx,DC=xx";
        $justthese = array("ou", "sn", "givenname", "mail");
        $ldapconn = ldap_connect($ldapserver) or die("Could not connect to LDAP server.");
        $u =  explode("\\", $data);
        $data = $u[1];
        ldap_set_option($ldapconn, LDAP_OPT_PROTOCOL_VERSION, 3);
        if($ldapconn) {
                $ldapbind = ldap_bind($ldapconn, $ldapuser, $ldappass) or die ("Error trying to bind: ".ldap_error($ldapconn));
                if ($ldapbind) {
                        $result = ldap_search($ldapconn,$ldaptree, "(cn=" .$data .")",$justthese) or die ("Error in search query: ".ldap_error($ldapconn));
                        $data = ldap_get_entries($ldapconn, $result);
        //return json_encode($data);
        return $data;
                } else {
                        throw new EnricherException('LDAP bind failed...');
                        }
        }
        ldap_close($ldapconn);
}
}

**Comment by vladiber** [comment]
<?php

namespace FOO;

/**
 * IP Enricher
 * Return GeoIP information on an IP address.
 * @package FOO
 */
class AD_Enricher extends Enricher {
    public static $TYPE = 'user';

    public static function process($data) {

        set_time_limit(30);
        error_reporting(E_ALL);
        ini_set('error_reporting', E_ALL);
        ini_set('display_errors',1);

        $ldapserver = 'server-ip';
        $ldapuser      = 'cn=xxxx,cn=xxx,dc=xx,dc=xx';
        $ldappass     = 'pass';
        $ldaptree    = "DC=xx,DC=xx";
        $justthese = array("ou", "sn", "givenname", "mail");
        $ldapconn = ldap_connect($ldapserver) or die("Could not connect to LDAP server.");
        $u =  explode("\\", $data);
        $data = $u[1];

        ldap_set_option($ldapconn, LDAP_OPT_PROTOCOL_VERSION, 3);
        if($ldapconn) {
                $ldapbind = ldap_bind($ldapconn, $ldapuser, $ldappass) or die ("Error trying to bind: ".ldap_error($ldapconn));
                if ($ldapbind) {
                        $result = ldap_search($ldapconn,$ldaptree, "(cn=" .$data .")",$justthese) or die ("Error in search query: ".ldap_error($ldapconn));
                        $data = ldap_get_entries($ldapconn, $result);
        //return json_encode($data);
        return $data;

                } else {
                        throw new EnricherException('LDAP bind failed...');
                        }

        }
        ldap_close($ldapconn);

}
}

**Comment by vladiber** [comment]
Ok , got it!!!  The problem is the data returned as multidimensional array. After flatting the array its working. Many thanks. 
Now the problem is renderer , how to render the data in alert view ? 
I'm using the latest release 1.3.3.

**Comment by kiwiz** [comment]
Nice. See [here](https://github.com/etsy/411/blob/master/docs/Development/NewEnricherRendererType.md#setup-renderer) for instructions on adding new renderers.

Since you're trying to render a table, you can probably just copy most of the logic here: https://github.com/etsy/411/blob/master/htdocs/assets/js/views/renderer/mac.js

**Comment by vladiber** [comment]
Thanks.
The last question is how to implement SEL expression in Source link on notification tab.
maybe some example , which variables i can use ?

**Comment by gromit6891** [comment]
Any examples for the Source link SEL expression - variables etc.
