### ISSUE TITLE
extra htdocs/release.tgz in release-es5x.tgz

### ISSUE THREAD

**Issue by phaer** [etsy/411#129]
The [es5x release of version 1.4.0]( https://github.com/etsy/411/releases/download/v1.4.0/release-es5x.tgz) includes a `release.tgz` in `htdocs` which is not there in the source repo and seems to includes a release of the master branch. I guess its an oversight?

**Comment by kiwiz** [comment]
Thanks! That explains why the es5x release was 2x bigger. I've uploaded a fixed version.
