### ISSUE TITLE
no cookie or nonce with proxy auth

### ISSUE THREAD

**Issue by phaer** [etsy/411#132]
Hi,

I can't submit any POST requests after switching to proxy auth because there's no valid nonce. FAQ mentions the possibility of multiple cookies, but I got none and - looking at the source - it seems like a nonce is only generated with cookies and cookies are only set for cookie auth?

**Comment by kiwiz** [comment]
@phaer Can you see if this fixed it?

**Comment by phaer** [comment]
@kiwiz Yes, it is. Thanks for the quick response!
