### ISSUE TITLE
Error when run migration (release5x)

### ISSUE THREAD

**Issue by tatdatpham** [etsy/411#133]
I got error when run **bin/migration.php** (ubuntu 16.04)

```
except [NONE] Errno 2: "require(/var/www/411/vendor/autoload.php): failed to open stream: No such file or directory" at [/var/www/411/phplib/411bootstrap.php:57] 0:[require() called at [/var/www/411/phplib/411bootstrap.php:57]] 1:[require_once() called at [/var/www/411/bin/migration.php:7]]
PHP Fatal error:  require(): Failed opening required '/var/www/411/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/411/phplib/411bootstrap.php on line 57
```

Don't see file called **/vendor/autoload.php**

**Comment by kiwiz** [comment]
Is this an upgrade? Have you run `composer install`?

**Comment by tatdatpham** [comment]
Ya, thank you support, my mistake, dont run composer. 
I installed success 411, created site and user but when i access 411 from browser, i got error 
![image](https://user-images.githubusercontent.com/3429970/29962181-778236ee-8f2c-11e7-8097-b5c2f839aa08.png)

**Comment by kiwiz** [comment]
Did you install from source? If so, you need to run `npm install`, `bower install`, `grunt prod`.

**Comment by tatdatpham** [comment]
Thanks @kiwiz  . It worked!
I got some another error. 
`"Undefined index: alerts" at [/var/www/411/phplib/ESClient.php:52]"`
My config.php has no mention of a **alert** index (since we don't use that default). 
Maybe config dont reload right?. How can do it?

**Comment by kiwiz** [comment]
The `alerts` is required by 411. It contains a copy of all the alerts for fast queries (and dashboards).

**Comment by mayuraadya** [comment]
I'm still facing the same issue 👎
