### ISSUE TITLE
Timestamp still shows UTC time instead of local time

### ISSUE THREAD

**Issue by AGirin** [etsy/411#135]
Changed /admin to my local time from UTC. Alerts still have UTC time stamp:

![image](https://user-images.githubusercontent.com/5177657/29896478-c544d0ca-8da2-11e7-9654-0a6611648ca1.png)

**Comment by kiwiz** [comment]
Hi, can you check your user settings at `/user/ID`? It's possible an override of UTC is defined there. I did a quick test and I do get non-UTC timestamps.

**Comment by AGirin** [comment]
Sure. I'll test.

**Comment by AGirin** [comment]
You were right. It was defined there as well. Changed it to my time zone and everything looks great now. Thanks!
