### ISSUE TITLE
Need query regarding security related alerts

### ISSUE THREAD

**Issue by sathishdsgithub** [etsy/411#137]
Hi team,

I'm new to 411 . I would like to know if 411 has the capability to create alert for the following type of use cases. I have listed some of them for example. 

- Network Port scan detection (cardinality based)

- Alert based on specific string match and multiple email alert options 

I would also like to go through some sample 411 ESquery rule for reference.

**Comment by kiwiz** [comment]
Cardinality aggs are supported, so you can do something like `host:10.0.0.1 | agg:cardinality term:port`

**Comment by sathishdsgithub** [comment]
@kiwiz

Can you share some sample rules for example.

**Comment by kiwiz** [comment]
Yup, check out https://github.com/kiwiz/esquery/ for examples of usage.

**Comment by sathishdsgithub** [comment]
@kiwiz 

- Do we have any standard procedure to install and setup 411 in Centos machine?  I tried with the installation method but unable to perfomr `bin/migration.phpand bin/create_site.php`.

-  Where do we specify the elasticseach nod IP address in 411. I'm using graylog not logstash . In my scenario I have installed  elasticsearch on the same 411 server. But i get below error

```
No alive nodes found in your cluster

Error: Uncaught TypeError: Cannot use 'in' operator to search for 'success' in <br /> <b>Fatal error</b>: Uncaught Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster in /var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:51 Stack trace: #0 /var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(71): Elasticsearch\ConnectionPool\StaticNoPingConnectionPool-&gt;nextConnection() #1 /var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(89): Elasticsearch\Transport-&gt;getConnection() #2 /var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(229): Elasticsearch\Transport-&gt;performRequest('HEAD', '/_template/411_...', Array, NULL, Array) #3 /var/www/411/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection-&gt;Elasticsearch\Connections\{closure}(Array) #4 /var/www/411/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise-&gt;then(Object(Closure), NULL, NULL) #5 /var/ in <b>/var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php</b> on line <b>51</b><br />
```

![image](https://user-images.githubusercontent.com/19161126/30284421-8817afde-9738-11e7-96c6-c87b0076b2a4.png)
