### ISSUE TITLE
no [query] registered for [filtered]

### ISSUE THREAD

**Issue by fojac** [etsy/411#138]
Hi,
First of all, thanks for this great piece of software! Very useful here.
I had a question regarding the support for ES > 5.x. When testing a (very simple!) search I get a "no [query] registered for [filtered] error."
It seems that the filtered method was deprecated with ES 5.x. ( https://stackoverflow.com/questions/40519806/no-query-registered-for-filtered ). Does this ring a bell to you?
Is there anything I can change on my side?
Best,
John

**Comment by kiwiz** [comment]
Thanks. :] Sanity check: are you running the `es-5x` branch?

**Comment by fojac** [comment]
Yes, absolutely, the latest from elastic.co (5.5.2).

**Comment by fojac** [comment]
There is a dependency on git when using composer: should be added to the doc.
I'd also suggest a reminder in the doc to send people to the proper branch for those using 5.x Elasticsearch.

**Comment by fojac** [comment]
Working like a charm now, thanks!

**Comment by kiwiz** [comment]
Np! Added a note to the setup doc.
