### ISSUE TITLE
Script or SMS alert

### ISSUE THREAD

**Issue by qianghaohao** [etsy/411#139]
Hi,
   Does 411 support the scrip alert or sms alert? I want to custom my own alarm channel, does is support that? Just like the Zabbix alert setting.

**Comment by quintanilhar** [comment]
Hey @qianghaohao, You can create your own alert targets, I found the #71 PR where the Pagerdutty target was added and you might use as a guide implementing your own. 

Let me know if you have any doubts implementing your target.

**Comment by qianghaohao** [comment]
Hi @quintanilhar, Thanks for your reply. That means i need to write php code to implement? If 411 supports scripts target, that would be wonderful. In script, we can alert whatever we want, such as email, sms, phone and so one. I am not familiar with php, but i will have a try, thank you.

**Comment by kiwiz** [comment]
@qianghaohao It sounds like the Pagerduty target may do what you want. You can specify a callback url in 411 and configure your alerting prefs on the Pagerduty site.

**Comment by qianghaohao** [comment]
@kiwiz Ok, thank you. Another question, it seems that 411 can't specify the index what i want to search. So where to specify the Es index name to search?

**Comment by quintanilhar** [comment]
Hey @qianghaohao, you can create as many indexes as your needs, just create a new key following this structure https://github.com/etsy/411/blob/master/config_example.php#L116. 

ex.:

```
    'logstash' => [
        'hosts' => ['http://localhost:9200'],
        'index_hosts' => [],
        'ssl_cert' => null,
        'index' => '[logstash-]Y.m.d',
        'date_based' => true,
        'date_interval' => 'd',
        'date_field' => '@timestamp',
        'date_type' => null,
        'src_url' => null,
    ],
    'mynewindex' => [
        'hosts' => ['http://localhost:9200'],
        'index_hosts' => [],
        'ssl_cert' => null,
        'index' => 'mynewindex',
        'date_based' => true,
        'date_interval' => 'd',
        'date_field' => '@mydatefield',
        'date_type' => null,
        'src_url' => null,
    ],
```
