### ISSUE TITLE
SearchException: No alive nodes found in your cluster

### ISSUE THREAD

**Issue by sathishdsgithub** [etsy/411#141]
@kiwiz 
I'm using elasticsearch on port 9200 with the below IP address. In the 411 console, it says no live hosts and I'm unable to create a query.

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      1160/dnsmasq
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2777/sshd
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      1501/mongod
tcp6       0      0 :::8080                 :::*                    LISTEN      97083/docker-proxy
tcp6       0      0 192.168.96.157:9200     :::*                    LISTEN      7346/java
tcp6       0      0 192.168.96.157:9300     :::*                    LISTEN      7346/java
tcp6       0      0 :::22                   :::*                    LISTEN      2777/sshd
tcp6       0      0 192.168.96.157:8855     :::*                    LISTEN      7578/java
tcp6       0      0 192.168.96.157:5566     :::*                    LISTEN      7578/java
tcp6       0      0 192.168.96.157:12900    :::*                    LISTEN      7578/java
tcp6       0      0 127.0.0.1:9350          :::*                    LISTEN      7578/java
tcp6       0      0 192.168.96.157:9000     :::*                    LISTEN      7578/java
```
```
root@ubuntu:/opt/411-docker# curl -XGET 'http://192.168.96.157:9200'
{
  "name" : "Blink",
  "cluster_name" : "graylog",
  "cluster_uuid" : "KSma-dJxTVW97Jwm0ttlRA",
  "version" : {
    "number" : "2.4.5",
    "build_hash" : "c849dd13904f53e63e88efc33b2ceeda0b6a1276",
    "build_timestamp" : "2017-04-24T16:18:17Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.4"
  },
  "tagline" : "You Know, for Search"
}

```

```
  # Configuration for the 411 Alerts index.
    'alerts' => [
        'hosts' => ['http://192.168.96.157:9200'],
        'index_hosts' => [''],
        'ssl_cert' => null,
        'index' => null,
        'date_based' => false,
        'date_interval' => null,
        'date_field' => 'alert_date',
        'date_type' => null,
        'src_url' => null,
    ],
    # Configuration for the logstash index that 411 queries.
    'logstash' => [
        'hosts' => ['http://192.168.96.157:9200'],
        'index_hosts' => [''],
        'ssl_cert' => null,
        'index' => '[logstash-]Y.m.d',
        'date_based' => true,
        'date_interval' => 'd',
        'date_field' => '@timestamp',
        'date_type' => null,
        'src_url' => null,
    ],

    'graylog_0' => [
        'hosts' => ['http://192.168.96.157:9200'],
        'index_hosts' => [''],
        'ssl_cert' => null,
        'index' => '[logstash-]Y.m.d',
        'date_based' => true,
        'date_interval' => 'd',
        'date_field' => '@timestamp',
        'date_type' => null,
        'src_url' => null,
    ],

```

![image](https://user-images.githubusercontent.com/19161126/30324762-c4dd42f6-97df-11e7-9ef9-a725a3fa09dc.png)

![image](https://user-images.githubusercontent.com/19161126/30325099-0faa50fc-97e1-11e7-8867-ca213ca9668f.png)

**Comment by quintanilhar** [comment]
Hi @sathishdsgithub, is there any index called "[logstash-]Y.m.d" in your elasticsearch? As I can see in your image you should replace by elastalert_status or graylog_0 that is the existent indexes.

**Comment by sathishdsgithub** [comment]
@quintanilhar 

As recommended I modified the index name as graylog_0 but still my es health status is bad (red).

my config.php as shown below

```
<?php

/**
 * 411 configuration file
 *
 * Rename this to 'config.php' and modify.
 */
$config = [];

/**
 * Authentication configuration
 */
$config['auth'] = [
    'proxy' => [
        /**
         * Whether to enable proxy auth.
         * IT IS VERY INSECURE TO ENABLE THIS IF 411 is not run behind an auth proxy.
         */
        'enabled' => false,
        /**
         * The name of the header the proxy is setting.
         */
        'header' => null,
        /**
         * Whether to automatically create users who are authenticated.
         */
        'auto_create' => false,
        /**
         * Email domain for automatically created users.
         */
        'domain' => null,
    ],
    'api' => [
        /**
         * Whether to enable api access to 411.
         */
        'enabled' => true
    ]
];

/**
 * Database configuration
 */
$config['db'] = [
    /**
     * A PDO compatible DSN. See https://secure.php.net/manual/en/pdo.drivers.php for details.
     * SQLite is the default configuration but MySQL is also supported. To configure the latter,
     * you'll need a dsn like the following: 'mysql:host=localhost;dbname=fouroneone'.
     */
    'dsn' => 'sqlite:' . realpath(__DIR__ . '/data.db'),
    /**
     * The user name for connecting to the database.
     */
    'user' => 'root',
    /**
     * The password for connecting to the database. Optional if the PDO driver doesn't
     * require a password.
     */
    'pass' => null,
];


/****
 *
 * Search type configuration
 * Note: All hostnames should specify protocol!
 *
 ***/

/**
 * Elasticsearch search type
 */
$config['elasticsearch'] = [
    /**
     * Each entry in this array represents an Elasticsearch source that 411 can query.
     *
     * 'hosts': An array of hosts powering your ES cluster.
     * 'index_hosts': An array of hosts to use for indexing (if different from 'hosts').
     * 'ssl_cert': Path to an ssl certificate if your cluster uses HTTPS.
     * 'index': The index to query. Leave as null to query all indices.
     *          If the index is date_based, accepts index patterns. (Otherwise, it's taken literally)
     *          Any characters wrapped by [] will be taken literally.
     *          All other characters are interpretted via PHP's date formatting syntax.
     *          See https://secure.php.net/manual/en/function.date.php for details.
     * 'date_based': Whether to generate an index name according to a date-based index pattern.
     * 'date_interval': If the index is date_based, this defines the indexing pattern interval.
     *                  'h' - Hourly.
     *                  'd' - Daily.
     *                  'w' - Weekly.
     *                  'm' - Monthly.
     *                  'y' - Yearly.
     * 'date_field': The field to use for doing date-based queries.
     * 'date_type': The format of the date field.
     *              null - Automatically detect and parse. Should work most of the time!
     *              '@' - Parse as a UNIX timestamp.
     *              '#' - Parse as a UNIX timestamps (in milliseconds).
     *              All other strings are interpretted via PHP's date formatting syntax.
     * 'src_url': A format string for generating default source links.
     *            Requires the following format specifiers: 's', 'd', 'd'.
     *            Ex: 'https://localhost/?query=%s&from=%d&to=%d'
     */

    # Configuration for the 411 Alerts index.
    'alerts' => [
        'hosts' => ['http://192.168.96.157:9200'],
        'index_hosts' => [],
        'ssl_cert' => null,
        'index' => '411_alerts_1',
        'date_based' => false,
        'date_interval' => null,
        'date_field' => 'alert_date',
        'date_type' => null,
        'src_url' => null,
    ],
    # Configuration for the logstash index that 411 queries.
    'logstash' => [
        'hosts' => ['http://192.168.96.157:9200'],
        'index_hosts' => [],
        'ssl_cert' => null,
        'index' => 'graylog_0',
        'date_based' => true,
        'date_interval' => 'd',
        'date_field' => '@timestamp',
        'date_type' => null,
        'src_url' => null,
    ],
];

/**
 * Graphite
 *
 * Configure to allow querying Graphite.
 */
$config['graphite'] = [
    /**
     * Each entry in this array represents a Graphite source that 411 can query.
     *
     * 'host': The hostname for your Graphite instance.
     */
    'graphite' => [
        'host' => null,
    ],
];

/**
 * ThreatExchange
 * See https://developers.facebook.com/products/threat-exchange for details.
 *
 * Configure to allow querying ThreatExchange.
 */
$config['threatexchange'] = [
    /**
     * The api token for connecting to ThreatExchange.
     */
    'api_token' => null,
    /**
     * The api secret for connecting to ThreatExchange.
     */
    'api_secret' => null,
];


/****
 *
 * Target configuration
 *
 ***/

/**
 * Jira
 *
 * Fill in to enable Jira integration.
 */
$config['jira'] = [
    /**
     * The hostname for your Jira instance.
     */
    'host' => null,
    /**
     * The username for connecting to Jira.
     */
    'user' => null,
    /**
     * The password for connecting to Jira.
     */
    'pass' => null,
];

/**
 * Slack
 *
 * Fill in to enable Slack integration.
 */
$config['slack'] = [
    /**
     * A webhook url to push Alerts to.
     * See https://api.slack.com/incoming-webhooks for details.
     */
    'webhook_url' => null
];

```
root@ubuntu:/opt/411-docker# docker run -p 8080:80 407b8c3affd6
2017-09-13 10:41:58,727 CRIT Supervisor running as root (no user in config file)
2017-09-13 10:41:58,736 INFO supervisord started with pid 1
2017-09-13 10:41:59,745 INFO spawned: 'cron' with pid 10
2017-09-13 10:41:59,759 INFO spawned: 'apache2' with pid 11
2017-09-13 10:42:01,323 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-09-13 10:42:01,323 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-09-13 10:42:58,365 CRIT reaped unknown pid 27)
2017-09-13 10:42:58,487 CRIT reaped unknown pid 35)
2017-09-13 10:42:58,535 CRIT reaped unknown pid 33)
2017-09-13 10:42:58,708 CRIT reaped unknown pid 43)
^C2017-09-13 10:45:45,101 WARN received SIGINT indicating exit request
2017-09-13 10:45:45,102 INFO waiting for cron, apache2 to die
2017-09-13 10:45:45,197 INFO stopped: apache2 (exit status 0)
2017-09-13 10:45:45,198 INFO stopped: cron (terminated by SIGTERM)
root@ubuntu:/opt/411-docker# docker run -p 8080:80 407b8c3affd6
2017-09-13 10:45:47,433 CRIT Supervisor running as root (no user in config file)
2017-09-13 10:45:47,438 INFO supervisord started with pid 1
2017-09-13 10:45:48,441 INFO spawned: 'cron' with pid 10
2017-09-13 10:45:48,443 INFO spawned: 'apache2' with pid 11
2017-09-13 10:45:49,520 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-09-13 10:45:49,521 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-09-13 10:48:43,855 CRIT reaped unknown pid 32)
2017-09-13 10:49:23,962 CRIT reaped unknown pid 45)
2017-09-13 10:49:24,002 CRIT reaped unknown pid 53)
2017-09-13 10:50:03,982 CRIT reaped unknown pid 62)

```

```
![image](https://user-images.githubusercontent.com/19161126/30373711-d9e1f5be-989f-11e7-842c-a4f6fd626561.png)

![image](https://user-images.githubusercontent.com/19161126/30373763-0bcad21c-98a0-11e7-884a-e421da4aff0e.png)

**Comment by quintanilhar** [comment]
Good, it is almost done, can you show the schema of this index please? You need to configure the date field:

```php
'date_based' => true, // usually is false
'date_interval' => 'd', // try as null
'date_field' => '@timestamp', // the date field in your index
'date_type' => null, // usually is null
```

**Comment by sathishdsgithub** [comment]
@quintanilhar 

Is this something your asking about?
```

{
"_index": "graylog_0",
"_type": "message",
"_id": "f60ac1d0-92dc-11e7-b254-000c2982a0e2",
"_version": 1,
"_score": 1,
"_source": {
"gl2_remote_ip": "192.168.96.157",
"srx-destination-address": "192.168.1.10",
"gl2_remote_port": 39458,
"source": "192.168.96.157",
"gl2_source_input": "59afa9218ec8161d9aad6e9b",
"srx-ip-address": "10.66.0.55",
"service-name": "None",
"srx-destination-port": "17075",
"srx-source-zone-name": "corporate",
"gl2_source_node": "6e3e4964-4439-4cbb-8e49-0baf1a006532",
"srx-protocol-id": "17",
"timestamp": "2017-09-06 08:25:37.339",
"level": -1,
"streams": [
"000000000000000000000001"
],
"message": "Apr 3 20:34:18 10.212.0.20 1 2017-04-03T20:34:17.602Z compt RT_FLOW - RT_FLOW_SESSION_DENY [junos@ source-address="188.1.1.2" source-port="56453" destination-address="192.168.1.10" destination-port="17075" service-name="None" protocol-id="17" icmp-type="0" policy-name="default-deny" source-zone-name="corporate" destination-zone-name="highwinds-inet" application="UNKNOWN" nested-application="UNKNOWN" username="N/A" roles="N/A" packet-incoming-interface="xe-4/0/1.10" encrypted="UNKNOWN" reason="policy deny"]",
"src-icmp-type": "0",
"srx-source-port": "56453",
"srx-policy-name": "default-deny",
"srx-rt-flow": "RT_FLOW_SESSION_DENY",
"srx-destination-zone-name": "highwinds-inet",
"facility": "Unknown",
"srx-source-address": "188.1.1.2"
}
}
```

**Comment by sathishdsgithub** [comment]
@quintanilhar 

I modified the config.php as per the schema still no luck .
```
 # Configuration for the logstash index that 411 queries.
    'logstash' => [
        'hosts' => ['http://192.168.96.157:9200'],
        'index_hosts' => [],
        'ssl_cert' => null,
        'index' => 'graylog_0',
        'date_based' => false,
        'date_interval' => 'null',
        'date_field' => 'timestamp',
        'date_type' => null,
        'src_url' => null,
    ],

```

![image](https://user-images.githubusercontent.com/19161126/30378211-0ac6258c-98b0-11e7-8a06-41a7f1103ac5.png)

**Comment by quintanilhar** [comment]
Try null without quotes for date_interval like this:

```php
'graylog' => [ // You can rename this by something that make more sense to you
        'hosts' => ['http://192.168.96.157:9200'],
        'index_hosts' => [],
        'ssl_cert' => null,
        'index' => 'graylog_0',
        'date_based' => false,
        'date_interval' => null,
        'date_field' => 'timestamp',
        'date_type' => null,
        'src_url' => null,
    ],
```
It may works now. :)

**Comment by quintanilhar** [comment]
I've tried this approach and it works for me:

![image](https://user-images.githubusercontent.com/1084316/30402753-42392d2a-98b5-11e7-9b1a-cf480e89a438.png)

![image](https://user-images.githubusercontent.com/1084316/30402809-5ed11e66-98b5-11e7-969d-35d1b2a70ed9.png)

:)

**Comment by sathishdsgithub** [comment]
@quintanilhar 

I'm tired of trying everything. Nothing working out. I'm using a docker to launch the 411 console.  Still the health status is red . 

![image](https://user-images.githubusercontent.com/19161126/30415844-86838204-9947-11e7-9617-34176db2b76c.png)

![image](https://user-images.githubusercontent.com/19161126/30415951-ee28879c-9947-11e7-8292-35125919c218.png)

![image](https://user-images.githubusercontent.com/19161126/30415974-0558a8f2-9948-11e7-8fce-757e1d675928.png)


![image](https://user-images.githubusercontent.com/19161126/30415988-11c26272-9948-11e7-8525-ddab14c3b082.png)

**Comment by kiwiz** [comment]
Make sure you've mounted the data volume appropriately. From your screenshots, 411 is using a default config file and not your modified one.

**Comment by nkshah** [comment]
i am getting below error: 
Error: Uncaught TypeError: Cannot use 'in' operator to search for 'success' in <br />
<b>Fatal error</b>:  Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception in /var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:681
Stack trace:
#0 /var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(640): Elasticsearch\Connections\Connection-&gt;tryDeserializeError(Array, 'Elasticsearch\\C...')
#1 /var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(561): Elasticsearch\Connections\Connection-&gt;tryDeserialize400Error(Array)
#2 /var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(262): Elasticsearch\Connections\Connection-&gt;process4xxError(Array, Array, Array)
#3 /var/www/411/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection-&gt;Elasticsearch\Connections\{closure}(Array)
#4 /var/www/411/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise-&gt;then(Object(Closure), NULL, NULL)
#5 /var/www/4 in <b>/var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php</b> on line <b>681</b><br />

Here is my config.php file : 

<?php

/**
 * 411 configuration file
 *
 * Rename this to 'config.php' and modify.
 */
$config = [];

/**
 * Authentication configuration
 */
$config['auth'] = [
    'proxy' => [
        /**
         * Whether to enable proxy auth.
         * IT IS VERY INSECURE TO ENABLE THIS IF 411 is not run behind an auth proxy.
         */
        'enabled' => false,
        /**
         * The name of the header the proxy is setting.
         */
        'header' => null,
        /**
         * Whether to automatically create users who are authenticated.
         */
        'auto_create' => false,
        /**
         * Email domain for automatically created users.
         */
        'domain' => null,
    ],
    'api' => [
        /**
         * Whether to enable api access to 411.
         */
        'enabled' => true
    ]
];
/**
 * Database configuration
 */
$config['db'] = [
    /**
     * A PDO compatible DSN. See https://secure.php.net/manual/en/pdo.drivers.php for details.
     * SQLite is the default configuration but MySQL is also supported. To configure the latter,
     * you'll need a dsn like the following: 'mysql:host=localhost;dbname=fouroneone'.
     */
    'dsn' => 'sqlite:' . realpath(__DIR__ . '/data.db'),
    /**
     * The user name for connecting to the database.
     */
    'user' => 'root',
    /**
     * The password for connecting to the database. Optional if the PDO driver doesn't
     * require a password.
     */
    'pass' => null,
];


/****
 *
 * Search type configuration
 * Note: All hostnames should specify protocol!
 *
 ***/
/**
 * Elasticsearch search type
 */
$config['elasticsearch'] = [
    /**
     * Each entry in this array represents an Elasticsearch source that 411 can query.
     *
     * 'hosts': An array of hosts powering your ES cluster.
     * 'index_hosts': An array of hosts to use for indexing (if different from 'hosts').
     * 'ssl_cert': Path to an ssl certificate if your cluster uses HTTPS.
     * 'index': The index to query. Leave as null to query all indices.
     *          If the index is date_based, accepts index patterns. (Otherwise, it's taken literally)
     *          Any characters wrapped by [] will be taken literally.
     *          All other characters are interpretted via PHP's date formatting syntax.
     *          See https://secure.php.net/manual/en/function.date.php for details.
     * 'date_based': Whether to generate an index name according to a date-based index pattern.
     * 'date_interval': If the index is date_based, this defines the indexing pattern interval.
     *                  'h' - Hourly.
     *                  'd' - Daily.
     *                  'w' - Weekly.
     *                  'm' - Monthly.
     *                  'y' - Yearly.
     * 'date_field': The field to use for doing date-based queries.
     * 'date_type': The format of the date field.
     *              null - Automatically detect and parse. Should work most of the time!
     *              '@' - Parse as a UNIX timestamp.
     *              '#' - Parse as a UNIX timestamps (in milliseconds).
     *              All other strings are interpretted via PHP's date formatting syntax.
     * 'src_url': A format string for generating default source links.
     *            Requires the following format specifiers: 's', 'd', 'd'.
     *            Ex: 'https://localhost/?query=%s&from=%d&to=%d'
     */
    # Configuration for the 411 Alerts index.
    'alerts' => [
        'hosts' => ['https://de6e6e67a5feaafbb98e8e2b610c8954.us-east-1.aws.found.io:9243'],
        'index_hosts' => [],
        'ssl_cert' => null,
        'index' => null,
        'date_based' => false,
        'date_interval' => null,
        'date_field' => 'alert_date',
        'date_type' => null,
        'src_url' => null,
    ],
    # Configuration for the logstash index that 411 queries.
    'logstash' => [
        'hosts' => ['https://de6e6e67a5feaafbb98e8e2b610c8954.us-east-1.aws.found.io:9243'],
        'index_hosts' => [],
        'ssl_cert' => null,
        'index' => '[cidbpurchases]Y.m.d',
        'date_based' => true,
        'date_interval' => 'd',
        'date_field' => '@timestamp',
        'date_type' => null,
        'src_url' => null,
    ],
];

/**
 * Graphite
 *
 * Configure to allow querying Graphite.
 */
$config['graphite'] = [
    /**
     * Each entry in this array represents a Graphite source that 411 can query.
     *
     * 'host': The hostname for your Graphite instance.
     */
    'graphite' => [
        'host' => null,
    ],
];
/**
 * ThreatExchange
 * See https://developers.facebook.com/products/threat-exchange for details.
 *
 * Configure to allow querying ThreatExchange.
 */
$config['threatexchange'] = [
    /**
     * The api token for connecting to ThreatExchange.
     */
    'api_token' => null,
    /**
     * The api secret for connecting to ThreatExchange.
     */
    'api_secret' => null,
];


/****
 *
 * Target configuration
 *
 ***/

/**
 * Jira
 *
 * Fill in to enable Jira integration.
 */
$config['jira'] = [
    /**
     * The hostname for your Jira instance.
     */
    'host' => null,
    /**
     * The username for connecting to Jira.
     */
    'user' => null,
    /**
     * The password for connecting to Jira.
     */
    'pass' => null,
];
/**
 * Slack
 *
 * Fill in to enable Slack integration.
 */
$config['slack'] = [
    /**
     * A webhook url to push Alerts to.
     * See https://api.slack.com/incoming-webhooks for details.
     */
    'webhook_url' => null
];

**Comment by nkshah** [comment]
Hello,

I am using docker image 411-latest, i change config.php file under /data dir, 

`<?php

/**
 * 411 configuration file
 *
 * Rename this to 'config.php' and modify.
 */
$config = [];

/**
 * Authentication configuration
 */
$config['auth'] = [
    'proxy' => [
        /**
         * Whether to enable proxy auth.
         * IT IS VERY INSECURE TO ENABLE THIS IF 411 is not run behind an auth proxy.
         */
        'enabled' => false,
        /**
         * The name of the header the proxy is setting.
         */
        'header' => null,
        /**
         * Whether to automatically create users who are authenticated.
         */
        'auto_create' => false,
        /**
         * Email domain for automatically created users.
         */
        'domain' => null,
    ],
    'api' => [
        /**
         * Whether to enable api access to 411.
         */
        'enabled' => true
    ]
];
/**
 * Database configuration
 */
$config['db'] = [
    /**
     * A PDO compatible DSN. See https://secure.php.net/manual/en/pdo.drivers.php for details.
     * SQLite is the default configuration but MySQL is also supported. To configure the latter,
     * you'll need a dsn like the following: 'mysql:host=localhost;dbname=fouroneone'.
     */
    'dsn' => 'sqlite:' . realpath(__DIR__ . '/data.db'),
    /**
     * The user name for connecting to the database.
     */
    'user' => 'root',
    /**
     * The password for connecting to the database. Optional if the PDO driver doesn't
     * require a password.
     */
    'pass' => null,
];


/****
 *
 * Search type configuration
 * Note: All hostnames should specify protocol!
 *
 ***/
/**
 * Elasticsearch search type
 */
$config['elasticsearch'] = [
    /**
     * Each entry in this array represents an Elasticsearch source that 411 can query.
     *
     * 'hosts': An array of hosts powering your ES cluster.
     * 'index_hosts': An array of hosts to use for indexing (if different from 'hosts').
     * 'ssl_cert': Path to an ssl certificate if your cluster uses HTTPS.
     * 'index': The index to query. Leave as null to query all indices.
     *          If the index is date_based, accepts index patterns. (Otherwise, it's taken literally)
     *          Any characters wrapped by [] will be taken literally.
     *          All other characters are interpretted via PHP's date formatting syntax.
     *          See https://secure.php.net/manual/en/function.date.php for details.
     * 'date_based': Whether to generate an index name according to a date-based index pattern.
     * 'date_interval': If the index is date_based, this defines the indexing pattern interval.
     *                  'h' - Hourly.
     *                  'd' - Daily.
     *                  'w' - Weekly.
     *                  'm' - Monthly.
     *                  'y' - Yearly.
     * 'date_field': The field to use for doing date-based queries.
     * 'date_type': The format of the date field.
     *              null - Automatically detect and parse. Should work most of the time!
     *              '@' - Parse as a UNIX timestamp.
     *              '#' - Parse as a UNIX timestamps (in milliseconds).
     *              All other strings are interpretted via PHP's date formatting syntax.
     * 'src_url': A format string for generating default source links.
     *            Requires the following format specifiers: 's', 'd', 'd'.
     *            Ex: 'https://localhost/?query=%s&from=%d&to=%d'
     */
    # Configuration for the 411 Alerts index.
    'alerts' => [
        'hosts' => ['https://de6e6e67a5feaafbb98e8e2b610c8954.us-east-1.aws.found.io:9243'],
        'index_hosts' => [],
        'ssl_cert' => null,
        'index' => null,
        'date_based' => false,
        'date_interval' => null,
        'date_field' => 'alert_date',
        'date_type' => null,
        'src_url' => null,
    ],
    # Configuration for the logstash index that 411 queries.
    'logstash' => [
        'hosts' => ['https://de6e6e67a5feaafbb98e8e2b610c8954.us-east-1.aws.found.io:9243'],
        'index_hosts' => [],
        'ssl_cert' => null,
        'index' => '[cidbpurchases]Y.m.d',
        'date_based' => true,
        'date_interval' => 'd',
        'date_field' => '@timestamp',
        'date_type' => null,
        'src_url' => null,
    ],
];

/**
 * Graphite
 *
 * Configure to allow querying Graphite.
 */
$config['graphite'] = [
    /**
     * Each entry in this array represents a Graphite source that 411 can query.
     *
     * 'host': The hostname for your Graphite instance.
     */
    'graphite' => [
        'host' => null,
    ],
];
/**
 * ThreatExchange
 * See https://developers.facebook.com/products/threat-exchange for details.
 *
 * Configure to allow querying ThreatExchange.
 */
$config['threatexchange'] = [
    /**
     * The api token for connecting to ThreatExchange.
     */
    'api_token' => null,
    /**
     * The api secret for connecting to ThreatExchange.
     */
    'api_secret' => null,
];


/****
 *
 * Target configuration
 *
 ***/

/**
 * Jira
 *
 * Fill in to enable Jira integration.
 */
$config['jira'] = [
    /**
     * The hostname for your Jira instance.
     */
    'host' => null,
    /**
     * The username for connecting to Jira.
     */
    'user' => null,
    /**
     * The password for connecting to Jira.
     */
    'pass' => null,
];
/**
 * Slack
 *
 * Fill in to enable Slack integration.
 */
$config['slack'] = [
    /**
     * A webhook url to push Alerts to.
     * See https://api.slack.com/incoming-webhooks for details.
     */
    'webhook_url' => null
];
`
i am getting below error : 

`Error: Uncaught TypeError: Cannot use 'in' operator to search for 'success' in <br />
<b>Fatal error</b>:  Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception in /var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:681
Stack trace:
#0 /var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(640): Elasticsearch\Connections\Connection-&gt;tryDeserializeError(Array, 'Elasticsearch\\C...')
#1 /var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(561): Elasticsearch\Connections\Connection-&gt;tryDeserialize400Error(Array)
#2 /var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(262): Elasticsearch\Connections\Connection-&gt;process4xxError(Array, Array, Array)
#3 /var/www/411/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection-&gt;Elasticsearch\Connections\{closure}(Array)
#4 /var/www/411/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise-&gt;then(Object(Closure), NULL, NULL)
#5 /var/www/4 in <b>/var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php</b> on line <b>681</b><br />`

Can you please help me?
