### ISSUE TITLE
Customizing Slack notifications?

### ISSUE THREAD

**Issue by lucasjkr** [etsy/411#142]
Not sure if I'm using an older version, but i'm not seeing a way to customize slack notification per alert? Is this possible, I'm only seeing a null message get pinged to my slack channel.

**Comment by kiwiz** [comment]
411 should include all of the alert info in Slack notifs. Is this not happening? If so, could you provide a screenshot of both the alert and the Slack notif?

**Comment by kiwiz** [comment]
@lucasjkr Is this still relevant?

**Comment by lucasjkr** [comment]
Hi!

I got it working, so that rather than getting "null" fields in slack, it sends all the search result to Slack.

I sill believe an included message would be good - just so that if you have lots of alerts getting triggered, you can add a desciptive sentence to lead off each event, making it easier to scan through.

**Comment by kiwiz** [comment]
@lucasjkr good idea. I've created #155 to track this.
