### ISSUE TITLE
Slack notification fails when using special characters for a search name

### ISSUE THREAD

**Issue by quintanilhar** [etsy/411#143]
Hi there!

When you use some special character for the search name, the Slack alert doesn't work getting the error below:

![411_bug_2](https://user-images.githubusercontent.com/1084316/30990774-e179699e-a478-11e7-8667-51c4a73d00a1.png)

The used name:

![411_bug_1](https://user-images.githubusercontent.com/1084316/30990777-e31c171a-a478-11e7-96a7-9591fd5588d1.png)

Have you already seen this before?

**Comment by kiwiz** [comment]
@quintanilhar was this issue resolved?

**Comment by quintanilhar** [comment]
It's working now, thank you @kiwiz !
