### ISSUE TITLE
Improving Slack alerts for HTTP Searches

### ISSUE THREAD

**Issue by quintanilhar** [etsy/411#144]
Hello!

How could we improve the Slack notifications to show the Search Name and some more details about the alert?

I'm receiving in this format today:

![image](https://user-images.githubusercontent.com/1084316/30991034-c22e8d02-a479-11e7-8a0a-d0c224f95f6b.png)

Thank you!

**Comment by kiwiz** [comment]
Looking into this issue.

**Comment by kiwiz** [comment]
To clarify, I'm looking into the Search Name issue.

What additional details would you like within Slack notifications?

**Comment by quintanilhar** [comment]
Today the search name is the only missing information in Slack alerts :)

**Comment by kiwiz** [comment]
I've pushed out a commit that might fix the Slack issues. Previously, we weren't escaping strings to Slack correctly (or even at all).

**Comment by quintanilhar** [comment]
Great @kiwiz, I'll test it. Thank you!

**Comment by quintanilhar** [comment]
In my case, I'd like to use the integration configuration that I did in Slack as display user in the messages. Do you know how could it be done?

I'm receiving the alerts as Catho (site name) with an exclamation icon:

![image](https://user-images.githubusercontent.com/1084316/31148031-fb181caa-a861-11e7-8857-e4198727df6e.png)

This is my configuration at Slack:
![image](https://user-images.githubusercontent.com/1084316/31148193-63a7de0e-a862-11e7-9b9d-d05af78828f1.png)

**Comment by kiwiz** [comment]
@quintanilhar was this issue resolved?

**Comment by quintanilhar** [comment]
Yes, it did but, now the link is missing:

![image](https://user-images.githubusercontent.com/1084316/31626705-867501ce-b289-11e7-82f5-76ab38a3d3f6.png)

Was it expected?

**Comment by kiwiz** [comment]
Hopefully fixed via the above.
