### ISSUE TITLE
New slack config option for username sender

### ISSUE THREAD

**Issue by quintanilhar** [etsy/411#146]
Hi!

May we have a config key in Slack configuration array to use or not the previous configuration for the user sender instead of using the site name with an alert icon?

For example, in my case, I've configured an username with a customized icon for my token:
![image](https://user-images.githubusercontent.com/1084316/31411903-822bc692-ade9-11e7-8fa0-077840f112f2.png)

But I'm receiving new messages as:
![image](https://user-images.githubusercontent.com/1084316/31411928-93d44b9e-ade9-11e7-98d2-e3e8339e1015.png)

The configuration could be:

```php
/**
 * Slack
 *
 * Fill in to enable Slack integration.
 */
$config['slack'] = [
    /**
     * A webhook url to push Alerts to.
     * See https://api.slack.com/incoming-webhooks for details.
     */
    'webhook_url' => null,
    'override_username' => true // default value as true for avoiding backward compatible problems
];
```

What do you think about? I can send a PR with this. :)

**Comment by kiwiz** [comment]
Sounds reasonable! I can take a stab at this.

**Comment by kiwiz** [comment]
Implemented support for `username` and `icon_emoji`.

**Comment by quintanilhar** [comment]
I've tested your implementation and everything works properly. 

Thank you @kiwiz!
