### ISSUE TITLE
Slack notifications: trailing '/' after hostname

### ISSUE THREAD

**Issue by rozling** [etsy/411#148]
Hi, thanks for the great project!

I'm seeing an issue with Slack notifications: the link to the alert page fails to render as a link in Slack, because 411 is adding an extra `/` character after the hostname, e.g:

`[<http://411.env.mydomain.net//alert/42|Alert>]`

I'm reasonably sure I entered the hostname without a trailing `/` while creating the site, but can't check where this is stored or change it from the UI

**Comment by kiwiz** [comment]
You can check by hitting http://411.env.mydomain.net/api/data via the `Host` field. There's no UI to change this, but you can update the `site` table in the database.

**Comment by kiwiz** [comment]
Opps, you're right. We're inserting an extra `/` in the `Site::urlFor` method.

**Comment by kiwiz** [comment]
I've pushed out a fix. Feel free to close this ticket if it resolves the problem.

**Comment by rozling** [comment]
Can confirm that this resolves the issue, thanks!
