### ISSUE TITLE
Configure Enrichers

### ISSUE THREAD

**Issue by sts** [etsy/411#149]
Currently the list of enrichers is hardcoded in `class Enricher`. We would like to disable IP and MAC Enrichers, so we don't leak information externally. What would be the best way to do so? Can we configure this somewhere?

**Comment by kiwiz** [comment]
Hi! You can create a file called `hook.php` in the root of the project to override the list of Enrichers. Something like this: (Untested)
```
<?php

Hook::register('init.pre', function($args) {
    Enrichers::$TYPES = ['Stacktrace_Enricher', 'Link_Enricher', 'Null_Enricher'];
});
```
I'm not sure that this is necessary, as the enrichers should only be accessible when logged into 411. Can you provide more details on that?

**Comment by sts** [comment]
Looks like there is a bug in Enricher.php:

```
    /**
     * Creates a new Enricher of the appropriate type.
     * @param string $type The type of the Enricher.
     * @return Enricher The new Enricher.
     */
    public static function getEnricher($type) {
        $types = self::getTypes();
        return Util::exists($types, $type) ? $types[$type] : 'null';
    }
```

Null is returned as string instead of null type.

This is how my hook.php looks like:

```
<?php

use FOO\Hook;
use FOO\Enricher;

Hook::register('init.pre', function($args) {
  Enricher::$TYPES = ['Link_Enricher'];
});
```

Exception:
`PHP Fatal error:  Uncaught Error: Class 'null' not found in /var/www/phplib/REST/Enrich.php:27`

**Comment by kiwiz** [comment]
@sts My bad, you were right. Fixed on master.
