### ISSUE TITLE
Sending alerts problem, sprintf

### ISSUE THREAD

**Issue by ily4** [etsy/411#150]
On test 411 site (latest version, migration from old site) i have problem with sending alerts.

`
Sat Oct 14 21:25:15.040703 2017] [:error] [pid 13783] [client ::1:47192] except [NONE] Errno 2: "sprintf(): Too few arguments" at [/var/www/411/phplib/Target/Slack.php:59] 0:[sprintf() called at [/var/www/411/phplib/Target/Slack.php:59]] 1:[FOO\\Slack_Target->process() called at [/var/www/411/phplib/Job/Search.php:207]] 2:[FOO\\Search_Job->processTargets() called at [/var/www/411/phplib/Job/Search.php:80]] 3:[FOO\\Search_Job->_run() called at [/var/www/411/phplib/REST/Searches.php:236]] 4:[FOO\\Searches_REST->execute() called at [/var/www/411/phplib/REST/Searches.php:62]] 5:[FOO\\Searches_REST->POST() called at [/var/www/411/phplib/REST.php:108]] 6:[FOO\\REST->route() called at [/var/www/411/htdocs/api/searches.php:6]], referer: http://my411.site.test/search/1
[Sat Oct 14 21:25:15.319249 2017] [:error] [pid 13783] [client ::1:47192] except [NONE] Errno 2: "http_build_query(): Parameter 1 expected to be Array or Object.  Incorrect value given" at [/var/www/411/phplib/Site.php:43] 0:[http_build_query() called at [/var/www/411/phplib/Site.php:43]] 1:[FOO\\Site->urlFor() called at [/var/www/411/phplib/Target/Slack.php:59]] 2:[FOO\\Slack_Target->process() called at [/var/www/411/phplib/Job/Search.php:207]] 3:[FOO\\Search_Job->processTargets() called at [/var/www/411/phplib/Job/Search.php:80]] 4:[FOO\\Search_Job->_run() called at [/var/www/411/phplib/REST/Searches.php:236]] 5:[FOO\\Searches_REST->execute() called at [/var/www/411/phplib/REST/Searches.php:62]] 6:[FOO\\Searches_REST->POST() called at [/var/www/411/phplib/REST.php:108]] 7:[FOO\\REST->route() called at [/var/www/411/htdocs/api/searches.php:6]], referer: http://my411.site.test/search/1
`
Test search is working correct.

**Comment by ily4** [comment]
Corrected mistake

**Comment by kiwiz** [comment]
Should be fixed via 5fc2849ed14399b3a20a0135d3fbae82b72c55f0. Can you test and close this issue if resolved?

**Comment by ily4** [comment]
Thank you kiwiz.
Tested and resolved.
