### ISSUE TITLE
Using Docker as local environment

### ISSUE THREAD

**Issue by quintanilhar** [etsy/411#152]
Hi @kiwiz,

I see that there is a repo with all the Docker config to get the 411 up and running, but it's in a separate repo (https://github.com/kiwiz/411-docker), why don't we have these configurations within 411 code?

It should facilitate a lot in how we can get the project up to start helping with the issues.

**Comment by kiwiz** [comment]
Hey there. I had it set up as a separate repo mostly for the README. I couldn't figure out how to get automatic builds working _and_ provide an alternate README on the dockerhub side.

**Comment by quintanilhar** [comment]
It's configurable in the Docker Hub page, you could create a different README file for this, what do you think?

**Comment by kiwiz** [comment]
I only see an option to configure the location of the Dockerfile. The README has to be in the same directory which won't work if I want the Dockerfile in the root. :[

**Comment by kiwiz** [comment]
Closing for now.
