### ISSUE TITLE
Elasticsearch 2.x and 5.x

### ISSUE THREAD

**Issue by AGirin** [etsy/411#159]
Hi!

We have three Elasticsearch clusters, two of them are 2.4 and one is 5.6. I see that you have different branch for 5.x support. Is it possible to merge this together somehow so we can monitor all clusters from one 411 instance? 

Thanks!

Andrew

**Comment by kiwiz** [comment]
Hi, unfortunately not. Composer doesn't provide a way to include 2 versions of a given library. Additionally, even if we managed that, we'd still run into namespacing issues. :[
