### ISSUE TITLE
"Unexpected error: error" when resolving alerts

### ISSUE THREAD

**Issue by ceeeekay** [etsy/411#163]
v1.4.0, es5x release.
This is a new install and all seems fine aside from this error.

Occurs when resolving single or multiple alerts. Alerts remain on the screen but are deleted, and disappear on refreshing the page.

Error log:

`[Fri Nov 17 14:03:24.108615 2017] [:error] [pid 3610] [client 192.168.2.72:40236] except [NONE] Errno 2: "array_key_exists(): The first argument should be either a string or an integer" at [/var/www/411/phplib/Util.php:36] 0:[array_key_exists() called at [/var/www/411/phplib/Util.php:36]] 1:[FOO\\Util::exists() called at [/var/www/411/phplib/Enricher.php:21]] 2:[FOO\\Enricher::getEnricher() called at [/var/www/411/phplib/Notification.php:288]] 3:[FOO\\Notification::groupAlerts() called at [/var/www/411/phplib/Notification.php:66]] 4:[FOO\\Notification::sendAlertActionEmail() called at [/var/www/411/phplib/REST/Alerts.php:352]] 5:[FOO\\Alerts_REST->setAlertFields() called at [/var/www/411/phplib/REST/Alerts.php:269]] 6:[FOO\\Alerts_REST->setAlertState() called at [/var/www/411/phplib/REST/Alerts.php:110]] 7:[FOO\\Alerts_REST->PUT() called at [/var/www/411/phplib/REST.php:109]] 8:[FOO\\REST->route() called at [/var/www/411/htdocs/api/alerts.php:6]], referer: https://411.kelp.wgtn.cat-it.co.nz/alerts?query=state:(0+1)
[Fri Nov 17 14:03:24.109235 2017] [:error] [pid 3610] [client 192.168.2.72:40236] PHP Fatal error:  Uncaught Error: Class 'null' not found in /var/www/411/phplib/Notification.php:289\nStack trace:\n#0 /var/www/411/phplib/Notification.php(66): FOO\\Notification::groupAlerts(Array, Array)\n#1 /var/www/411/phplib/REST/Alerts.php(352): FOO\\Notification::sendAlertActionEmail(Array, Object(FOO\\AlertLog), Array, Array)\n#2 /var/www/411/phplib/REST/Alerts.php(269): FOO\\Alerts_REST->setAlertFields(Array, Array, 6, 6, 2, 0)\n#3 /var/www/411/phplib/REST/Alerts.php(110): FOO\\Alerts_REST->setAlertState(Array)\n#4 /var/www/411/phplib/REST.php(109): FOO\\Alerts_REST->PUT(Array, Array)\n#5 /var/www/411/htdocs/api/alerts.php(6): FOO\\REST->route()\n#6 {main}\n  thrown in /var/www/411/phplib/Notification.php on line 289, referer: https://411.kelp.wgtn.cat-it.co.nz/alerts?query=state:(0+1)
`

**Comment by kiwiz** [comment]
Can you check if this is fixed on head? https://github.com/etsy/411/tree/es-5.x

**Comment by kiwiz** [comment]
Closed due to inactivity.
