### ISSUE TITLE
Failure on rotated indices

### ISSUE THREAD

**Issue by ceeeekay** [etsy/411#165]
Hi there,

411 is great, everything is great, except:

I'm indexing to Elasticsearch with Logstash, and every day at 00:00 UTC I get a failure alert for any Elasticsearch search types I have configured with daily indices (Y.m.d), and then a recovery alert 1 minute later, after the day's index has been created.  Obviously it's a race condition as the new index won't have been there at the exact moment that 411 tries to check it.

Is there anything I can do to prevent this?

v1.4.0, es5x release.

Thanks!

**Comment by kiwiz** [comment]
Hey there,

One option is to add a threshold to [Worker.php](https://github.com/etsy/411/blob/master/phplib/Worker.php) to only run jobs with older `target_dates` (Ex: Only run if the job is at least 1 minute old). Would you be willing to submit a PR for this?

**Comment by kiwiz** [comment]
Another (hacky) solution is to throw a sleep before `bin/worker.php` to give ES a chance to create the index.

**Comment by kiwiz** [comment]
Closing since there's not much we can do on the 411-side.
