### ISSUE TITLE
I am having an issue with /dev/urandom function with fopen, fread and fclose

### ISSUE THREAD

**Issue by siddhantjm** [etsy/411#170]
I got an error with the /dev/urandom used with fopen in random.php 
I got the error regarding the same and i'm not able to hit the website as the random key generated are of 10 interger numbers hence it throws Cookie Short exception. Can anyone help me with this? I'm using a windows PC bdw.
Thanks in Advance.

**Comment by kiwiz** [comment]
Is Linux an option? PHP7.0 has `random_bytes`, which is a cross platform way to get PRNs but I'd like to maintain PHP5 support.

**Comment by siddhantjm** [comment]
Yes. @kiwiz `random_bytes` did work fine. Thanks a ton.
