### ISSUE TITLE
Facing issue with an error on dashboard.

### ISSUE THREAD

**Issue by siddhantjm** [etsy/411#171]
I logged in to the website and I'm getting an error message which says "Processor has not run in more than 20 mins!" also along with this in the health section es[logstash], ping and graphite[graphite] are failing. I'm using Elasticsearch version 5.6.2, Kibana 5.6.2 and logstash 5.6.2. and when it comes to php I'm using 7.0 version because `/dev/urandom` is not supported by windows so I'm using `random_bytes` which is supported by php 7.0 and not by php 5.  So I needed a solution to rectify this error.
Thanks in advance.

**Comment by siddhantjm** [comment]
Also, I wanted to know how to know how to run crontab on windows. Because I was unable to run the crontab and I started the website.

**Comment by kiwiz** [comment]
Moved to gitter.
