### ISSUE TITLE
SQLSTATE[HY000]: General error: 1 table search_targets has no column named content

### ISSUE THREAD

**Issue by mourlos** [etsy/411#176]
On the latest build of 5.x when you create a new search and go to the advanced section to enable a target, the following error message appears when you click on `Save Filter and Targets`:

```SQLSTATE[HY000]: General error: 1 table search_targets has no column named content```

Tried to find any error messages but nothing indicates so far what is causing it.

**Comment by kiwiz** [comment]
Sorry, this was some development code that was active. I'm pushing out an updated version now.

**Comment by kiwiz** [comment]
Fixed in 1.4.2
