### ISSUE TITLE
mapping parser exception error 

### ISSUE THREAD

**Issue by EYMIST** [etsy/411#178]
Hello,

First of all thank you for making 411  :) . I was running this on 5.6.8 it was working flawless. Then i upgraded to 6.2.3 and installed the release.tgz (V1.4.2) but i am getting this error for some reason. Can anyone help ? 

[Fri Mar 23 07:35:15.440624 2018] [php7:notice] [pid 20494] [client 10.198.212.135:56573] except [NONE] Elasticsearch\\Common\\Exceptions\\BadRequest400Exception: "mapper_parsing_exception: No handler for type [string] declared on field [notes]" at [/var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:665] 0:[Elasticsearch\\Connections\\Connection->tryDeserializeError() called at [/var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:640]] 1:[Elasticsearch\\Connections\\Connection->tryDeserialize400Error() called at [/var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:561]] 2:[Elasticsearch\\Connections\\Connection->process4xxError() called at [/var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:262]] 3:[Elasticsearch\\Connections\\Connection->Elasticsearch\\Connections\\{closure}() called at [/var/www/411/vendor/react/promise/src/FulfilledPromise.php:25]] 4:[React\\Promise\\FulfilledPromise->then() called at [/var/www/411/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php:55]] 5:[GuzzleHttp\\Ring\\Future\\CompletedFutureValue->then() called at [/var/www/411/vendor/guzzlehttp/ringphp/src/Core.php:341]] 6:[GuzzleHttp\\Ring\\Core::proxy() called at [/var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:283]] 7:[Elasticsearch\\Connections\\Connection->Elasticsearch\\Connections\\{closure}() called at [/var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:159]] 8:[Elasticsearch\\Connections\\Connection->performRequest() called at [/var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php:105]] 9:[Elasticsearch\\Transport->performRequest() called at [/var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php:79]] 10:[Elasticsearch\\Endpoints\\AbstractEndpoint->performRequest() called at [/var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php:948]] 11:[Elasticsearch\\Namespaces\\IndicesNamespace->create() called at [/var/www/411/phplib/ESClient.php:107]] 12:[FOO\\ESClient->initializeIndex() called at [/var/www/411/phplib/ESClient.php:34]] 13:[FOO\\ESClient->__construct() called at [/var/www/411/phplib/Target/DB.php:22]] 14:[FOO\\DB_Target->__construct() called at [/var/www/411/phplib/Job/Search.php:73]] 15:[FOO\\Search_Job->_run() called at [/var/www/411/phplib/REST/Searches.php:212]] 16:[FOO\\Searches_REST->test() called at [/var/www/411/phplib/REST/Searches.php:60]] 17:[FOO\\Searches_REST->POST() called at [/var/www/411/phplib/REST.php:108]] 18:[FOO\\REST->route() called at [/var/www/411/htdocs/api/searches.php:6]], referer: http://10.122.62.63/searches/new?type=null

**Comment by alexwardle** [comment]
I am getting the same issue running version 1.4.2 on es 6.1.2.  It seems to be related to this issue https://github.com/elastic/elasticsearch-dsl-py/issues/804.  I thought maybe we could upgrade the elasticsearch-php library to v6, but the kiwiz/ecl library does not support appear to support v6 yet.

One possible workaround is creating 411 alerts index manually, as this issue only occurs when creating a new index.

**Comment by alexwardle** [comment]
Update: I confirmed the workaround is effective.  Run the following curl command to manually create the index template.  It will still return the deprecation notice, but it should succeed.
`curl -XPUT "http://localhost:9200/_template/411_alerts_wildcard" -H 'Content-Type: application/json' -d'
{
  "order": 0,
  "index_patterns": [
    "411_alerts_*"
  ],
  "settings": {},
  "mappings": {
    "_default_": {
      "properties": {
        "alert_date": {
          "type": "date",
          "format": "epoch_second"
        },
        "assignee_type": {
          "type": "long"
        },
        "assignee": {
          "type": "long"
        },
        "content": {
          "type": "object"
        },
        "source": {
          "type": "text"
        },
        "search_id": {
          "type": "long"
        },
        "state": {
          "type": "long"
        },
        "resolution": {
          "type": "long"
        },
        "escalated": {
          "type": "boolean"
        },
        "content_hash": {
          "type": "text"
        },
        "notes": {
          "type": "text"
        },
        "create_date": {
          "type": "date",
          "format": "epoch_second"
        },
        "update_date": {
          "type": "date",
          "format": "epoch_second"
        }
      }
    }
  },
  "aliases": {}
}'`

**Comment by kiwiz** [comment]
Tracking ES6.0 support in #179.
