### ISSUE TITLE
Set an "incident_key" on PagerDuty incidents to avoid duplication

### ISSUE THREAD

**Issue by eherot** [etsy/411#181]
Right now every alert that notifies PagerDuty will generate a new incident every time it fires. This is extremely annoying. Instead, a non-unique incident key, containing the name of the alert, should be specified when the event is triggered so that PD knows that the new alert is part of the same incident.

**Comment by kiwiz** [comment]
@eherot Check out the `es-5x` branch to test this out (Note the updated setup instructions https://github.com/etsy/411/blob/es-5.x/docs/Setup.md#install)
