### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by bardie** [etsy/411#182]
How do i test whether my current slack and mail setup is working. I have configured the slack webhook but i am not receiving any alerts. I am using the docker setup.

**Comment by kiwiz** [comment]
Does `docker logs` give you any useful info?

**Comment by bardie** [comment]
Managed to get Slack working, i just had to rebuild the docker image with the slack settings . What is currently pending is getting the email module to work

**Comment by kiwiz** [comment]
I couldn't figure out a general email-solution for the container, so the docker container doesn't work 100% out of the box atm.

This might work for your purposes: https://linuxconfig.org/configuring-gmail-as-sendmail-email-relay
