### ISSUE TITLE
Daily Rollup Email config

### ISSUE THREAD

**Issue by sql25951** [etsy/411#187]
Is it possible, or could it be made possible to configure the look and feel of **daily rollup** emails? Specifically we'd like to hide the _Recent Actions_ section and other sections as we actually email it out to people who dont want to know anything except the error messages in the body.

Ideally if we could add our own logo/color scheme too as additional thoughts on the idea.

**Comment by kiwiz** [comment]
Added basic support for this via 9382df568df8d158d5eff367a4fbcb5cadf0e8d0. Any template files in the `exttemplates` directory will now take precedence over the built in 411 templates.
