### ISSUE TITLE
Is 411's URL configurable?

### ISSUE THREAD

**Issue by lucasjkr** [etsy/411#188]
I've put 411 into my ELK Docker Container (using https://github.com/kiwiz/411-docker), and intended to serve it using Nginx as a reverse proxy, so that (https://my-url/kibana) leads to kibana and (https://my-url/411) leads to 411;

Kibana plays nicely in this arrangement, but 411 does not, it's still looking for files from the site root; Off the top of everyone's head, this easily configurable? Or are you open to a pull request to the base URL part of the config?

**Comment by kiwiz** [comment]
Hi. 411 assumes that it lives on the root of the domain. PRs to change this are welcome! You'll have to add a new field to `phplib/Site.php` and upgrade logic to `bin/migration.php`.

**Comment by kiwiz** [comment]
*I've replaced `master` with the `es-5.x` branch.

**Comment by lucasjkr** [comment]
Perfect, I will take a look in the next couple of days;
