### ISSUE TITLE
Node ping options

### ISSUE THREAD

**Issue by gromit6891** [etsy/411#189]
Having an issue within a Kubernetes environment where the Elasticsearch nodes can be pinged by name but 411 will only recognize if the IP address is used. Most likely an unusual ping response that is returned in this environment. For example when using the node name then you get the the error 'No nodes available' even though you can ping the node name. 
Can this option be modified so that 411 can do a different type of healthcheck on Elasticsearch, by doing an open port check, or a different type of TCP ping?

**Comment by kiwiz** [comment]
@gromit6891 If you disable the healthcheck, does 411 work otherwise?

**Comment by gromit6891** [comment]
I will try, how do you disable the healthcheck?

**Comment by kiwiz** [comment]
Try manually patching this function to just return true: https://github.com/etsy/411/blob/master/phplib/Search/Elasticsearch.php#L67
