### ISSUE TITLE
Issue in Alert Generation

### ISSUE THREAD

**Issue by Fr4g3roO** [etsy/411#192]
1.) Alert is not generated when  aggregation (agg) in query is used. P.S When I try to Test/Execute Search, results are shown but no alerts are generated.

Eg:  agg:terms field:cs6.keyword | agg:terms field:src.keyword | agg:terms field:dest.keyword.

2.) Also how do I specify only required fields when Count is chosen.

Thanks in Advance

**Comment by EYMIST** [comment]
@kiwiz we are facing the same issue

**Comment by kiwiz** [comment]
Hi, what version of ES & 411 are you using?
