### ISSUE TITLE
Noisy cron

### ISSUE THREAD

**Issue by ceeeekay** [etsy/411#21]
We're seeing cron output every minute as a result of running cron.php & worker.php.

It might be an idea to silence the scripts (or have a switch to do this) and/or modify the setup instructions to include `> /dev/null 2>&1` for the cron entry.

Cheers.

**Comment by kiwiz** [comment]
Noted in https://github.com/etsy/411/commit/12dcad0d8c1c350fca3afebe9762fdba4c730ee2.
