### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by zeroCrashOveride** [etsy/411#22]
Hey, have created a few users with "bin/create_user.php"
unfortunaly keep getting "Invalid credentials" errors on the login screen.

Could not find a way to check the logs or troubleshoot, any tips?

Regards,
AB

**Comment by tomerliberman** [comment]
+1

**Comment by kiwiz** [comment]
I just pushed e3495292ab23ed9224d8728c3c840f42338a2331 to make it easier to debug this.

Please pull and hit `YOURHOST/api/data`. The thing to check is the `"Host"` field. Does it say `'fouroneone'` or does it have an actual hostname?

**Comment by tomerliberman** [comment]
managed to solve it locally with a hostfile entry on my mac

when i tried loginng in with ip url it gave the above errors but when i came with a host header it worked.. 

e.g 
http://1.2.3.4/  didnt work
http://local411/ worked

**Comment by kiwiz** [comment]
You can also set the `411HOST` env var. I added some information via 4894d989e04b845d0d92997bc2cf69bb9caafbac.

**Comment by calh** [comment]
@kiwiz, was there a reason for choosing the `411HOST` environment variable name?  It's giving me a bit of a tough time because it's not a valid Bash variable name.  (Bash variables can't start with a number)  I wanted to set it in the system environment, then `PassEnv` with Apache.

**Comment by kiwiz** [comment]
@calh `FOOHOST` sounds like a placeholder variable. Nonetheless, I added support for either via 785c3938860f8f879d248705427b3e48d5397e69.
