### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by AGirin** [etsy/411#24]
How does email notification actually work? I would like to use smtp on my CentOS 6.6 to relay messages to our primary email server. Is this possible or do I need to use Exim?

Thanks!

Andrew

**Comment by kiwiz** [comment]
Do you have sendmail configured? 411 just calls the `mail()` function, so if everything is set up it should work.

**Comment by AGirin** [comment]
I think it is configured properly. I will test though and let you know.

**Comment by AGirin** [comment]
Yep, works fine. Sendmail was not running (I though I started it). Thanks!
