### ISSUE TITLE
Invalid credentials too with ssl on non standard port 8443

### ISSUE THREAD

**Issue by mareban** [etsy/411#25]
After a fresh install with the latest update, cannot login too !

except [NONE] FOO\\UnauthorizedException: "Invalid nonce specified" at [/var/www/411/phplib/REST.php:101] 0:[FOO\\REST->route()

/api/data give the right hostname:8443

Can someone help please ?

Thanks

**Comment by kiwiz** [comment]
Sorry, this should be fixed via 0580ce353d3b370705dc081fe92c9e6e21fa64a8 now.

**Comment by mareban** [comment]
Thanks for your help and quick reply, and for this useful project from Etsy !

Now it's ok.

All the best.
