### ISSUE TITLE
composer: ecl download fails

### ISSUE THREAD

**Issue by sbassan** [etsy/411#32]
composer.lock defines ecl url as './ecl' however that path doesn't exist, this causes composer install to fail.

`"dist": {
   "type": "path",
   "url": "./ecl",
   "reference": "565c5929ab503b6241c9fd6ddc65ea478a817f1e",
   "shasum": null
 }`

**Comment by kiwiz** [comment]
Whoops, should be fixed now.

**Comment by sbassan** [comment]
Thanks!
