### ISSUE TITLE
grunt requirejs task failing

### ISSUE THREAD

**Issue by sbassan** [etsy/411#33]
Running "requirejs:js" (requirejs) task
Error: ENOENT: no such file or directory, open '/411/htdocs/dist/js/views/searches/search/push.js'
In module tree:
    main
      app
        views/searches/search/load

{ [Error: Error: ENOENT: no such file or directory, open '/411/htdocs/dist/js/views/searches/search/push.js'
In module tree:
    main
      app
        views/searches/search/load

    at Error (native)
]
  originalError:
   { [Error: ENOENT: no such file or directory, open '/411/htdocs/dist/js/views/searches/search/push.js']
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/411/htdocs/dist/js/views/searches/search/push.js',
     fileName: '/411/htdocs/dist/js/views/searches/search/push.js',
     moduleTree: [ 'views/searches/search/load', 'app', 'main' ] } }
The command '/bin/sh -c grunt prod' returned a non-zero code: 1

**Comment by nevins-b** [comment]
Looks like maybe this file was supposed to added in e8f2f35b7daf449c285a9b1ff2e3477aa6aed447 but wasn't

**Comment by kiwiz** [comment]
Bleh. Leaked out from the push branch. Fixed b1629d8134ce2255b947a302d08876a4dfe485ef.
