### ISSUE TITLE
requirements of elasticsearch  1.5+ isnt correct

### ISSUE THREAD

**Issue by ChristiaanDouma** [etsy/411#35]
411 is using epoch_second pattern which isnt standard available in ES 1.5

**Comment by ChristiaanDouma** [comment]
See https://www.elastic.co/guide/en/elasticsearch/reference/1.5/mapping-date-format.html

**Comment by kiwiz** [comment]
Nice catch. I forgot to update this when I removed  support for 1.5. Fixed in 8ec2d6f.

**Comment by brennebeck** [comment]
@kiwiz does this effect the 1.0.1 release? As I'm trying to get that running but I'm getting errors that appear to be related to `epoch_second`. If so, I don't see a release/tag that would work?
