### ISSUE TITLE
Webhook/slack is giving a Target webhook/slack: Remote server returned 0

### ISSUE THREAD

**Issue by ChristiaanDouma** [etsy/411#36]
Hi,

I am trying to use the webhook capability but keep getting Target webhook: Remote server returned 0 on a slack webhook

**Comment by kiwiz** [comment]
Possibly related to #30. To confirm: You're using the Slack target and not the WebHook target?

**Comment by ChristiaanDouma** [comment]
I tried Both with the same result. Maybe i am using the wrong slack url. I used the slack incoming webhook. Btw, it does Work when i dont have a proxy in between

**Comment by kiwiz** [comment]
Interesting. How's this proxy set up?

**Comment by ChristiaanDouma** [comment]
Hmm, problem exists between keyboard and chair (my fault).
I had made a docker container which runs your great project but only set the proxy on buildtime and forgot to set the proxy settings on runtime.

so got the slack working webhook still giving the same error though.

**Comment by kiwiz** [comment]
It might be that curl isn't using the proxy settings.

Can you try adding those settings to https://github.com/etsy/411/blob/master/phplib/Target/Slack.php to test this? Example here: https://github.com/php-curl-class/php-curl-class/blob/master/examples/proxy.php

**Comment by kiwiz** [comment]
@ChristiaanDouma Both of those use the similar Curl logic. If this is still a problem, can you investigate what err curl is returning?

**Comment by ChristiaanDouma** [comment]
@kiwiz i got it solved. I having this problem in a docker container setup and set the http(s) proxy settings as environment settings.

**Comment by ChristiaanDouma** [comment]
hm, in cron couldnt get it working only by adding your suggested curl options

**Comment by kiwiz** [comment]
¯\_(ツ)_/¯ Does the ENV setting still work? If so, that's good enough.

**Comment by ChristiaanDouma** [comment]
I added the curl logic to Curl.php 
Also had to add verifyhost, verifypeer and no_proxy.

Now it works.

Maybe add these properties to the Config.php?

Grtz

**Comment by kiwiz** [comment]
@ChristiaanDouma What did you specify for the `no_proxy` opt?

**Comment by ChristiaanDouma** [comment]
I had to opt out our own interval servers.

**Comment by kiwiz** [comment]
Closing this for now. Tracking docker related things in #26
