### ISSUE TITLE
Switching from detailed to compact view produces and error

### ISSUE THREAD

**Issue by AGirin** [etsy/411#38]
![capture](https://cloud.githubusercontent.com/assets/5177657/19054895/0dd855ee-8987-11e6-9976-66bdb245034f.PNG)

When in the search view - try to switch from Detailed view to Compact view. I always get an error.

**Comment by kiwiz** [comment]
Is this still an issue?

**Comment by AGirin** [comment]
Yes, exactly the same error with all recent updates.

**Comment by kiwiz** [comment]
Does the error log show anything?

**Comment by AGirin** [comment]
Unfortunately no.

**Comment by kiwiz** [comment]
Does the developer console show any failed requests/Are there any errors in the server log?

**Comment by AGirin** [comment]
I have an update on this. So it does work in Chrome. It does not work in MS Edge browser. With Edge I get this:

![image](https://cloud.githubusercontent.com/assets/5177657/19528735/c9410af2-95f2-11e6-9193-95357cd5bf02.png)

Does this help?

**Comment by kiwiz** [comment]
Yup, that helps alot. I do all 411 development on Chrome.

**Comment by kiwiz** [comment]
Fixed.
