### ISSUE TITLE
Allow search searching across multiple ES clusters/indexes

### ISSUE THREAD

**Issue by nevins-b** [etsy/411#39]
Right now 411 only allows for, without changes to code outside config, searching a single index index prefix inside a single cluster.

It would be nice be able to configure multiple indexes or clusters then for each search specify against which indexes or clusters it should be executed against.

**Comment by kiwiz** [comment]
The plan is to implement this via #4.

As a side note: I added some experimental support for [ECL](https://github.com/kiwiz/ecl), which allows you to query any of the es clusters configured in 411.

**Comment by nevins-b** [comment]
Great! I'll close this issue in that case
