### ISSUE TITLE
Display timestamps on the frontend in a configurable timezone

### ISSUE THREAD

**Issue by mareban** [etsy/411#42]
Is it possible to have time in CEST instead of GMT Please ?

Thanks for your help.

**Comment by AGirin** [comment]
It would be great that this is controlled by the browser time zone. I am on CST and this is really confusing to see time in GMT.

**Comment by kiwiz** [comment]
I think this should be doable by modifying `formatDate` here: https://github.com/etsy/411/blob/master/htdocs/assets/js/util.js#L11

However, I'm clear on the consequences. This is very low priority for me and a PR would be welcome!

**Comment by mareban** [comment]
We cannot use 411 in prod with GMT time ! It would be nice if we can  have a solution please  :) ?

Thanks for your help.

**Comment by kiwiz** [comment]
https://github.com/etsy/411/blob/master/htdocs/assets/js/util.js#L11-L16
If you replace `toUTCString` with `toDateString`, it *might* work.

**Comment by kiwiz** [comment]
Pointers for anyone who works on this:
- A new option should be added to the Settings page
  - https://github.com/etsy/411/blob/master/htdocs/assets/templates/settings.html
  - https://github.com/etsy/411/blob/master/htdocs/assets/js/views/settings.js
  - http://momentjs.com/timezone/docs/#/data-loading/getting-zone-names/
- `formatDate` should account for user settings
  - https://github.com/etsy/411/blob/master/htdocs/assets/js/util.js#L11-L16

**Comment by kiwiz** [comment]
Finished up frontend implementation. Remaining:
- Templates (email)
- Search statistics modal
