### ISSUE TITLE
LDAP based authentication

### ISSUE THREAD

**Issue by mareban** [etsy/411#43]
Is it planned to manage users/groups from Active Directory please ?

Thanks for your help.

**Comment by kiwiz** [comment]
Not atm, but PRs would be considered for this. All the authentication logic happens in `phplib/Auth.php`, so most of the changes would be in there.

**Comment by kiwiz** [comment]
Probably solved with #95 in combination with something like https://github.com/exflickr/GodAuth.

**Comment by elvarb** [comment]
Would this work? 
https://github.com/bitly/oauth2_proxy

**Comment by kiwiz** [comment]
Took a quick look and it looks like it would. Just need to set the header field to `X-Forwarded-User` in 411's config.

**Comment by elvarb** [comment]
Very good, also highly recommend that project.
