### ISSUE TITLE
Email and Alerts Formatting

### ISSUE THREAD

**Issue by AGirin** [etsy/411#44]
It would be great if email formatting was a little bit better:

![image](https://cloud.githubusercontent.com/assets/5177657/19117883/354b6c38-8ae0-11e6-9bec-9c66926b5794.png)

Same with the view on Alerts page:

![image](https://cloud.githubusercontent.com/assets/5177657/19117938/66817086-8ae0-11e6-8bb7-76945270a344.png)

**Comment by kiwiz** [comment]
Table formatting is hard. :[ I think the only two options are tables that are looooooong or what we have currently.

**Comment by AGirin** [comment]
I kind of figured I have to remove some fields that I do not want to see. That actually makes things better. I think I will close the issue since it is kind of configurable with fields so it is not a big deal.
