### ISSUE TITLE
Alerts are not being removed for the searches that were deleted

### ISSUE THREAD

**Issue by AGirin** [etsy/411#45]
If I delete Search before I resolve all alerts that it produced those alerts are staying forever on Alerts page - no matter what I do (Resolve, Acknowledge etc):

![image](https://cloud.githubusercontent.com/assets/5177657/19118050/bfd3b2fc-8ae0-11e6-9bd4-9fa8dff7975a.png)

**Comment by kbiedermann** [comment]
They can be deleted manually from the elasticsearch index that should look something like: 411_alerts_1
Haven't figured out a better way yet

**Comment by kiwiz** [comment]
Not optimal, but you can delete that index and do a resync with
"bin/es_sync.php --site=1". I'll take a look at this when I have time.

**Comment by AGirin** [comment]
I was actually deleting index :-). But it would be harder to do when it is in actual production and more people use it.

**Comment by kiwiz** [comment]
It would be much easier to delete these alerts if we changed the type to encode the search id as well. Ex: `411_alerts_1/ping_1234` The downside is this would require a re-index.

**Comment by LFBernardo** [comment]
I am running a Siemonster instance with 411 included and there is no Elasticsearch index for the alerts. So the above solution doesn't work in this instance.

**Comment by LFBernardo** [comment]
Leaving this here for other Siemonster users that run into this problem

Open Rancher
Execute shell to es-client-1-1
Install curl  apk --no-cache add curl
curl -XDELETE 0:9200/411_alerts_1
Reload 411 page

**Comment by khulfreedos** [comment]
@LFBernardo - what does this commands do? Will this delete all the alerts including the Searches created? I have been trying to delete this but there has been no luck. Appreciate your help. Thanks!

![image](https://user-images.githubusercontent.com/29403934/31390792-65bb4b4a-ae07-11e7-9c3c-4c7226a906a8.png)

**Comment by LFBernardo** [comment]
@khulfreedos This will only delete the orphaned (all alerts) in your Elastic instance. The searches you have configured is stored elsewhere (in db if memory serves). It seems a bit nuke like to do to clean orphaned searches but I haven't been able to spend more time on it. If I come up with a better way to do it I will come share it here. I will also be posting howto's on my git page as well as on the Siemonster support site. 
P.S. your searches will be lost if you upgrade the 411 container, just bear that in mind.

**Comment by kiwiz** [comment]
Added a new job to delete Alerts via f6bfc4c798a2c18b969a2753dfb4af4d860b702e.
