### ISSUE TITLE
Add documentation on Groups

### ISSUE THREAD

**Issue by AGirin** [etsy/411#47]
![image](https://cloud.githubusercontent.com/assets/5177657/19121125/eb935d34-8aea-11e6-86d4-8edf87713f7e.png)

What is the difference between All and Rotation types? I can't find any info on this. 

Thanks!

**Comment by kiwiz** [comment]
There are some details here: https://github.com/etsy/411/blob/master/docs/GettingStarted.md#creating-a-new-user--adding-it-to-a-group

Leaving this open as a remind to add more details.

**Comment by kiwiz** [comment]
0af4b956c2936490de20d010a9fd216f764cc7a6
