### ISSUE TITLE
ES query does not work in Search

### ISSUE THREAD

**Issue by AGirin** [etsy/411#48]
Is this type of query supported by 411?

metrics.server_lag:[0 TO 86400]

It gives me an error. I assume it is either not supported or I need to use different syntax?

Thanks!

**Comment by kiwiz** [comment]
That syntax should be supported. Can you check your mappings for `metrics.server_lag`?

**Comment by AGirin** [comment]
You know it actually works for me now. Not sure what happened. I manually typed it in to the search filed and it worked. I pasted it previously from clipboard - maybe some special characters were present. I will close non-issue. Thanks!
