### ISSUE TITLE
Email Alerts

### ISSUE THREAD

**Issue by AGirin** [etsy/411#49]
I mentioned that alert and alert resolution have different subjects:

![capture](https://cloud.githubusercontent.com/assets/5177657/19126742/c49e13f6-8b01-11e6-8a1c-f577b09d4272.PNG)

[411] xxxx xxxxx marked Resolved (Not an issue) --> Resolution
[411] Zoom --> Alert

Ideally we would have them match as far as search name. So in this example I would see:

[411] **Zoom** xxxx xxxxx marked Resolved (Not an issue) --> Resolution
[411] Zoom --> Alert

In both cases we have name of the search. This is very important for systems like PagerDuty - I could match [411] Zoom to be able to open/close PagerDuty tickets. Right now it is problematic as any resolution would close any ticket in PagerDuty since we do not have search name in the subject.

**Comment by AGirin** [comment]
Also - I mentioned that links in the emails are not clickable - I have to open browser to see the alert. Somehow Outlook does not like the formatting. Here is an example:

![image](https://cloud.githubusercontent.com/assets/5177657/19194758/4ea412bc-8c74-11e6-9827-8d0133debba8.png)

View is not selectable, Compare Alerts does not work.

**Comment by kiwiz** [comment]
The first one is difficult, because you can close alerts from multiple searches in the same request (which would be shown?).

For the second problem, do you mind doing some debugging for me? (We don't use Outlook internally)

**Comment by AGirin** [comment]
Sure. Let me know what you need.

**Comment by kiwiz** [comment]
Try modifying the alert_list.php file. That defines the actual html for
each row.
