### ISSUE TITLE
Email has HTTPS link even though we do not use HTTPS

### ISSUE THREAD

**Issue by AGirin** [etsy/411#50]
We do not use HTTPS but all links in the email alert point to HTTPS:

![image](https://cloud.githubusercontent.com/assets/5177657/19127513/e6afe07a-8b04-11e6-901a-cea83492adf4.png)

**Comment by kiwiz** [comment]
Probably not going to fix this. You can replace all instances of `https` in `templates` with `http`.

**Comment by AGirin** [comment]
Sorry, I don't see any http there. I see <?= $base_url ?>/. Where do I find that?

**Comment by kiwiz** [comment]
My bad, this is defined in `Notification.php`.
