### ISSUE TITLE
Autoclose of the Alert

### ISSUE THREAD

**Issue by AGirin** [etsy/411#51]
Does Autoclose feature work? I selected to close Alert in 1 minute but they sit there forewver until I manually close them.

![image](https://cloud.githubusercontent.com/assets/5177657/19132881/387d3478-8b1b-11e6-9981-e3306ff39adf.png)

**Comment by kiwiz** [comment]
The Autoclose jobs are set to run every hour. We usually use them with large time spans (several days). Can you describe your workflow/why you'd like Alerts to be closed instantly?

**Comment by AGirin** [comment]
I was just testing and mentioned and Autoclose does not do anything. I was expecting to see test alert resolved automatically but no luck. So if it runs only on an hourly basis - why allow me to select 1 minute Autoclose timeout? 

I will try with an hour and see if this works.

**Comment by AGirin** [comment]
Ok, so I think there is a bug: The alert was autoclose - or at least it said so here:

![image](https://cloud.githubusercontent.com/assets/5177657/19198349/4ab1a74a-8c84-11e6-9fd9-77c2ce0a0b5c.png)

But Alert is still displayed on Alerts page and it is still Open. My guess that Autoclose does not really update a ticket.

**Comment by AGirin** [comment]
Also - when 411 autoclosed the alert it did not send an email about it. When I closed the alert myself I also did not get an email (but I do get them if I do not use Autoclose). Just an additional point.

**Comment by AGirin** [comment]
And to describe the workflow I am trying to get:

1. Low priority alert is created and 411 sends email to PagerDuty.
2. PagerDuty opens low priority ticket based on the email
3. Alert sits there for more than a day
4. 411 closes the ticket and sends email to PagerDuty 
5. PagerDuty closes the ticket.

This way we can keep 411 clean from noise and also use PagerDuty as our primary source of alerts. We don't have to manage 411 and PagerDuty.

**Comment by kiwiz** [comment]
> why allow me to select 1 minute Autoclose timeout?
Mostly laziness. :]

Nice catch on alerts not closing, this is indeed a bug. I'm not sure if autoclosed Alerts should fire off emails. On one hand, there should be no element of surprise (alerts disappearing), on the other, will people care?

Re: your workflow: I've added support for API keys to 411 (documentation is admittedly sparse atm). Maybe that could help with implementing this workflow?

**Comment by kiwiz** [comment]
@AGirin Going to close this as I've the alerts are now updated in the index.
