### ISSUE TITLE
Home Page does not show any Actions

### ISSUE THREAD

**Issue by AGirin** [etsy/411#54]
I mentioned that graph Actions never shows anything:

![image](https://cloud.githubusercontent.com/assets/5177657/19167088/d300314e-8bcf-11e6-903a-4ab17f368ff7.png)

Even though I acknowledged and resolved a lot of alerts.

Could that be a bug related to SQLite/MySQL differences?

**Comment by kiwiz** [comment]
Should be fixed via bda5541c776f50cf0d06266f25fd8337c4e8ca54. Can you confirm?

**Comment by AGirin** [comment]
I pulled, ran grunt prod and still see no updates there.

**Comment by AGirin** [comment]
Which table are you getting this from? I want to make sure it exists on my side. Maybe it is missing when we were having issues with SQLite to MySQL migration?

**Comment by kiwiz** [comment]
It's via the `alerts` and `alert_logs` tables. I need to set up a MySQL instance for testing this at some point.

**Comment by AGirin** [comment]
Yea, I see both tables.

**Comment by AGirin** [comment]
Confirmed - woks fine now. Thanks a lot!
