### ISSUE TITLE
No email notification

### ISSUE THREAD

**Issue by mareban** [etsy/411#55]
Hi,

I've made a new install with the latest version, configure mysql instead of a previous Sqlite default install,  and  now i don't have an SQL syntax error with the LIMIT clause ! Multiple-indicies is OK too !
I've deleted the 411 indices in elasticsearch to start from a clean situation !

A search is configured to send notification once a day with the cron notation  and is enabled (high priority) !
I don't know what i'm doing wrong, but i can't receive any email  notification ???
If i execute the search everything is ok, and i receive the email notification ! 

My local smtp is up and running (Postfix) ...

Can someone help me please ?

Thanks for your help.

PS : The enable button is not so clear with the default colors (enable vs disable) !

**Comment by kiwiz** [comment]
Can you confirm that the Search in question is running? You can see this by hitting the "Jobs" button on the Search configuration page.

**Comment by mareban** [comment]
Hello,

All is fine now, and jobs too, the only problem i have is the date format (CEST instead of GMT), so when the search is created i've to substract 2 hours :) !

Thanks for your help.

**Comment by kiwiz** [comment]
Nice. :] See #42 for progress on that issue.
