### ISSUE TITLE
Send to Jira fails

### ISSUE THREAD

**Issue by AGirin** [etsy/411#58]
I tried Jira functionality and I can see my projects and tasks but when I click send I just get an error - failed to send Alert. Not errors in the log files.

**Comment by kiwiz** [comment]
Do you get a 'Remote server returned' error?

**Comment by AGirin** [comment]
![image](https://cloud.githubusercontent.com/assets/5177657/19198474/f2c9f306-8c84-11e6-9656-f95d415abc61.png)

This is what I see.

**Comment by kiwiz** [comment]
Can you try again after pulling? I changed up the logging a bit.

**Comment by AGirin** [comment]
Did that. Got Error 400 now.

**Comment by kiwiz** [comment]
One more time. You should get the actual body that JIRA is returning in the error msg.

**Comment by AGirin** [comment]
Go this now:

![image](https://cloud.githubusercontent.com/assets/5177657/19275475/7ea34442-8f99-11e6-92a5-39438e7eebea.png)

And I see this error in the log:

except [NONE] Errno 4096: "Object of class stdClass could not be converted to string" at [/var/www/411/phplib/Target/Jira.php:78] 0:[sprintf() called at [/var/www/411/phplib/Target/Jira.php:78]] 1:[FOO\\Jira_Target::createIssue() called at [/var/www/411/phplib/Target/Jira.php:52]] 2:[FOO\\Jira_Target->process() called at [/var/www/411/phplib/REST/Alerts.php:214]] 3:[FOO\\Alerts_REST->sendAlerts() called at [/var/www/411/phplib/REST/Alerts.php:83]] 4:[FOO\\Alerts_REST->POST() called at [/var/www/411/phplib/REST.php:108]] 5:[FOO\\REST->route() called at [/var/www/411/htdocs/api/alerts.php:6]], referer: http://test.test.com/alerts?query=state:(0+1)

**Comment by kiwiz** [comment]
Oh, looks like it's returning an object. Can you add a `print_r` around line 76 in `Target/Jira.php`?

**Comment by AGirin** [comment]
I think I am doing something wrong. Does this look like what you wanted?

 `print_r;`
        `if($curl->httpStatusCode < 200 || $curl->httpStatusCode >= 300) {
            throw new TargetException(sprintf('Remote server returned %d: %s: %s', $curl->httpStatusCode, $curl->httpErrorMessage, $ret));
        }`

**Comment by kiwiz** [comment]
`print_r($ret);`, rather.

**Comment by AGirin** [comment]
Yea, I tried that already and nothing new in the logs. 

This is what I got with tcpdump:

![image](https://cloud.githubusercontent.com/assets/5177657/19283386/3994e1f8-8fb7-11e6-81cc-44c6a8a2ab4b.png)

**Comment by AGirin** [comment]
Ok, I got it to work. First I must have assignee specified and second - actually specify the right assignee. I forgot that our Jira uses AD usernames and I was specifying the wrong one. 

Not sure if this makes sense but maybe **assignee** must be require field?

**Comment by kiwiz** [comment]
I think it might depend on your JIRA project's config. We could probably load the full list of users via `https://JIRA/rest/api/latest/user/search?username=%&maxResults=10000`. Not sure if it's worth the request.

**Comment by AGirin** [comment]
That would be great I think. At least it would help us a lot.

**Comment by AGirin** [comment]
https://github.com/etsy/411/issues/50 --> Just want to make sure you saw my last question. I could not find any references to https in templates. Jira ticket has a link to the issue but it is also https. I can fix this on my side but where exactly is this base_url?
