### ISSUE TITLE
Suggestion about Regex in the Advanced/search

### ISSUE THREAD

**Issue by AGirin** [etsy/411#60]
I find myself constantly making the same mistake: I create Regex exception (so I will not see the error again) and also forget to click on Include to uncheck it

![image](https://cloud.githubusercontent.com/assets/5177657/19242999/5f105c8c-8edb-11e6-8f19-c9aad73a5adc.png)

It would be great if default action was to exclude as it seems to me most people would want to have Regex to exclude event not to include (maybe I am wrong on that though). Or maybe ask at the end of the process - Do you really want to include> or something like that.

**Comment by kiwiz** [comment]
Hmm, I think include more reasonable, like with how `grep` works by default.

**Comment by AGirin** [comment]
I guess it depends on how we approach monitoring: Include all and remove noise, or only include specific events you want to see. I am testing with number one approach so Include needs to be unchecked all the time. But for the second approach default works just fine. I'll close the issue.
