### ISSUE TITLE
Merge Branch Push Login Error

### ISSUE THREAD

**Issue by gromit6891** [etsy/411#64]
With the latest release there is an api error when logging in:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to FOO\\Models_REST::GET() must be of the type array, none given, called in /var/www/411/phplib/REST/Data.php on line 106 and defined in /var/www/411/phplib/REST/Models.php:288\nStack trace:\n#0 /var/www/411/phplib/REST/Data.php(106): FOO\\Models_REST->GET()\n#1 /var/www/411/phplib/REST/Data.php(16): FOO\\Data_REST->generateUsers()\n#2 /var/www/411/phplib/REST.php(107): FOO\\Data_REST->GET(Array)\n#3 /var/www/411/htdocs/api/data.php(6):FOO\\REST->route()\n#4 {main}\n  thrown in /var/www/411/phplib/REST/Models.php on line 288, referer:
```

**Comment by kiwiz** [comment]
Did you run `bin/migration.php` after upgrading? There were a few schema changes. :]

**Comment by gromit6891** [comment]
Yes, the output was - Migrating from 1.1.0 to 1.1.0 - Migration complete. As a check I can see that an api field has been added to the 'users' table.

**Comment by kiwiz** [comment]
Hopefully fixed via f1d61174a6ca63abf7b58a352237a3c53fea4ccf.

**Comment by gromit6891** [comment]
Yes, that fixed it. Just a note - to allow composer install you have to have php-ast installed. Maybe add to requirements.

**Comment by kiwiz** [comment]
Thanks, I've pushed a small documentation change to address this.
