### ISSUE TITLE
Support for millisecond timestamps 

### ISSUE THREAD

**Issue by kbiedermann** [etsy/411#72]
Need support for `date_field` in milliseconds within 411. Able to execute successful searches, but unable to send result to 411 alert index in elasticsearch. Get `mapper_parsing_exception` and `illegal_argument_exception` on the `alert_date` field for Invalid format.

**Comment by kiwiz** [comment]
Should be fixed via e4df5965b30c0821a78bd0125c1d774b9a2327da. Define the new `date_type` attribute in your config file (check `config_example.php` for details).

**Comment by kbiedermann** [comment]
Even if the date field in ES does not have a # or @? 
I don't see in the changes the date field for the alert index being set to type epoch_millis so I'm confused if it using milliseconds or converting milliseconds to seconds.

**Comment by kiwiz** [comment]
Should be all resolved.
