### ISSUE TITLE
PagerDuty Integration Question

### ISSUE THREAD

**Issue by AGirin** [etsy/411#73]
I see that PagerDuty "send" was introduced recently. Any plans to actually create PD incidents based on the search? So instead of sending email we would just use PD API to open incident (as well as close it when issues is resolved in 411).

**Comment by kiwiz** [comment]
Not atm, I think the API should be sufficient for that functionality. The `/api/alert/switch` endpoint will accomplish this, but it'll require a third service to parse and forward requests from Pagerduty.
