### ISSUE TITLE
Errors upgrading from 1.0.1 to 1.1.0

### ISSUE THREAD

**Issue by profilernz** [etsy/411#78]
bin/migration.php 
except [NONE] Errno 2: "require(/var/www/411/vendor/autoload.php): failed to open stream: No such file or directory" at [/var/www/411/phplib/411bootstrap.php:57] 0:[require() called at [/var/www/411/phplib/411bootstrap.php:57]] 1:[require_once() called at [/var/www/411/bin/migration.php:7]]
PHP Fatal error:  require(): Failed opening required '/var/www/411/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/411/phplib/411bootstrap.php on line 57

**Comment by profilernz** [comment]
/usr/local/bin/composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for etsy/phan ^0.6.0 -> satisfiable by etsy/phan[0.6].
    - etsy/phan 0.6 requires php >=7.0 -> your PHP version (5.6.27) does not satisfy that requirement.

PS: Setup.md lists PHP 5.5 as a minimum version...

**Comment by profilernz** [comment]
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for etsy/phan ^0.6.0 -> satisfiable by etsy/phan[0.6].
    - etsy/phan 0.6 requires ext-ast * -> the requested PHP extension ast is missing from your system.

**Comment by kiwiz** [comment]
Whoops, I forgot to update the upgrade docs. PHP 5.5 is still supported. Just run `composer update --no-dev --optimize-autoloader` and you should be good to go. (phan is a dev dependency)

**Comment by profilernz** [comment]
I did use --no-dev as per my 3rd post, and was still getting errors...
so:
composer install --no-dev --optimize-autoloader
works fine when you are first installing but then:
composer update --no-dev --optimize-autoloader
doesn't:
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for etsy/phan ^0.6.0 -> satisfiable by etsy/phan[0.6].
    - etsy/phan 0.6 requires ext-ast * -> the requested PHP extension ast is missing from your system.

**Comment by kiwiz** [comment]
I think I misunderstood what `install` and `update` do. I *think* `composer install` should be sufficient to get all dependencies?

**Comment by profilernz** [comment]
Yeah, for my fresh PHP7 setup, "install" worked fine.
It's just that I noticed that "update" wouldn't work on PHP 5.6, and then that it wouldn't also work on 7.0 post-upgrade.
I running 411 with no issues, just thought I'd highlight this issue.

**Comment by kiwiz** [comment]
Coolbeans. Thanks for the note and apologies for the trouble. Update the docs and will close this out!
