### ISSUE TITLE
Jira user list is empty

### ISSUE THREAD

**Issue by AGirin** [etsy/411#80]
![image](https://cloud.githubusercontent.com/assets/5177657/20121811/1689247a-a5d9-11e6-9cbe-665a799ae855.png)

We sync our users with crowd from AD. For some reasons Jira users are not populating into the list and I am unable to send issues to Jira. I was able to do so before when I was just typing name manually. Can we have a combination of manual and automatic lists?

**Comment by kiwiz** [comment]
Fixed.
