### ISSUE TITLE
cron.php: except [NONE] Errno 2: "array_key_exists(): The first argument should be either a string or an integer" at 

### ISSUE THREAD

**Issue by ChristiaanDouma** [etsy/411#85]
When running cron.php I get an error (in a docker container)
I have got an elasticsearch 2.4 version configured.

root@host:/var/www/411# /var/www/411/bin/cron.php
[+] Scheduler: 1479239860
[+] Maintenance
[+] Search Health
except [NONE] Errno 2: "array_key_exists(): The first argument should be either a string or an integer" at [/var/www/411/vendor/kiwiz/ecl/src/Util.php:36] 0:[array_key_exists() called at [/var/www/411/vendor/kiwiz/ecl/src/Util.php:36]] 1:[ECL\Util::exists() called at [/var/www/411/vendor/kiwiz/ecl/src/Util.php:19]] 2:[ECL\Util::get() called at [/var/www/411/vendor/kiwiz/ecl/src/Util.php:138]] 3:[ECL\Util::generateDateIndices() called at [/var/www/411/phplib/Search/Elasticsearch.php:76]] 4:[FOO\Elasticsearch_Search->isWorking() called at [/var/www/411/phplib/Scheduler.php:341]] 5:[FOO\Scheduler->health() called at [/var/www/411/phplib/Scheduler.php:146]] 6:[FOO\Scheduler->processSite() called at [/var/www/411/bin/cron.php:45]]

**Comment by AGirin** [comment]
Same issue as in https://github.com/etsy/411/issues/83

**Comment by kiwiz** [comment]
Fixed.
