### ISSUE TITLE
Ability to export searches and upload them manually

### ISSUE THREAD

**Issue by CrazyLlama** [etsy/411#87]
I'm unsure if there's a way to currently a way to export/upload searches manually in JSON format (whether on the front or back end) but I think this feature would be incredibly useful for several environments that may require similar base search patterns.

I'm very sorry if this is already do-able and I've just missed it.

**Comment by kiwiz** [comment]
There are a few ways you could accomplish this:

1. The Searches page has a "Clone" button for each search. That would probably work if you only have a small number of searches.
2. You could capture the POST request to `/api/search` when creating a search and replay with modifications.
3. There's an API if you want to do this programmatically. Docs on the API are [here](https://github.com/etsy/411/blob/master/docs/API.md) (and a bit sparse). You can inspect the request (as in opt 2) for details on the format.
