### ISSUE TITLE
Non-admin users can disable what searches generate alerts

### ISSUE THREAD

**Issue by scrow123** [etsy/411#89]
in a multi user system, non-admin accounts can disable what searches generate alerts, is there a way of locking down the enabled/disabled check boxes so users do not have the ability to disable this? If not is there way to add this in? Allowing anyone to disable searches could lead to certain security events being missed & a breach occurring.
thanks!

**Comment by kiwiz** [comment]
You can disable all modifications for non-admins by changing these calls to `Auth::isAdmin()`:
https://github.com/etsy/411/blob/master/phplib/REST/Searches.php#L69-L75

**Comment by scrow123** [comment]
brilliant will check it out now 👍 
thanks mate!

**Comment by scrow123** [comment]
Hi,
i have (finally) tried this out and it does not appear to work. We are using MYSQL as the database on a separate node. Do you think this could be an issue?
thanks :)

**Comment by kiwiz** [comment]
Do you mean normal users can make changes anyway? Just to test, try swapping those lines with `return false` and see if that blocks writes for all users.

**Comment by scrow123** [comment]
No that didnt work unfortunately :(
I have a few non-admin users that can create modify and delete searches even with return Auth::Admin. Is there any session data or cache within the document root that needs to be flushed? we are not using any caching on our end like redis.
There is a users.php file, do the same changes need to be made in this file too?

**Comment by kiwiz** [comment]
I just tried making the change and it definitely works on my environment. Ideas:
- What version of 411 are you using? I pushed out `v1.2` recent, so it might be worth updating to see if that the issue
- Maybe you're modifying a separate copy of the code?
