### ISSUE TITLE
Timeout on GET-ting /api/data/

### ISSUE THREAD

**Issue by CrazyLlama** [etsy/411#91]
The actual error I'm receiving is:

require.js:formatted:56 Uncaught Error: /api/data HTTP status: 504(…)s.onreadystatechange @ main.js:formatted:30306

Which refers to the line:
     
r > 399 && 600 > r ? (a = new Error(e + " HTTP status: " + r),

In the function:

 s.onreadystatechange = function(i) {
                  var r, a;
                  4 === s.readyState && (r = s.status || 0,
                  r > 399 && 600 > r ? (a = new Error(e + " HTTP status: " + r),
                  a.xhr = s,
                  n && n(a)) : t(s.responseText),
                  m.onXhrComplete && m.onXhrComplete(s, e))
                                                           }

It may be a usage issue as it's being used in https://siemonster.com/ 
However I'm unsure of where to go from there :(

**Comment by kiwiz** [comment]
Weird. Siemonster seems to be running an old version of 411: https://github.com/siemonster/411. I'd ask them for help this as I don't know how their integration works.
