### ISSUE TITLE
Unable to select all alerts so I can close them at once

### ISSUE THREAD

**Issue by AGirin** [etsy/411#94]
I have a lot of alerts 
![image](https://cloud.githubusercontent.com/assets/5177657/20938745/d14c8f16-bbb1-11e6-933a-4b6876d5da2d.png)

and when I am trying to select all of them I get 'Unexpected error: error' after some time and nothing is selected. It is really hard to close all these alerts even if I load 1000 at a time. 

I do not see any errors in the logs unfortunately.

**Comment by kiwiz** [comment]
Dang, that's a huge number of alerts. I think the php script is timing out while trying to retrieve all the alerts. Can you confirm whether the server is returning any useful info (chrome dev tools: network tab).

**Comment by AGirin** [comment]
Here we go:

![image](https://cloud.githubusercontent.com/assets/5177657/21024110/f292dd04-bd48-11e6-9e4a-a13547383edb.png)

**Comment by kiwiz** [comment]
Do you get an error in the PHP logs?
