### ISSUE TITLE
Did you plan to support MS-SQL?

### ISSUE THREAD

**Issue by IzekChen** [etsy/411#96]
as the title, we are looking for this project.
but we only use MS-SQL.
So we want to know did you have a plan to support MS-SQL ?

**Comment by kiwiz** [comment]
@IzekChen no plans to support MS-SQL but PRs would be welcome! Have you tested 411 with a MS-SQL database?

**Comment by IzekChen** [comment]
ok, thank you. we did not try 411 with MS-SQL. But I think I will.
